/**
 * Curated skincare product records for /skincare-checker (not wired to UI yet).
 *
 * TODO: Later move this database to Firebase or CSV import when product count grows to 1000+.
 */

export type SkincareProductType =
  | "moisturizer"
  | "serum"
  | "sunscreen"
  | "cleanser"
  | "toner"
  | "acne treatment"
  | "barrier repair";

export type SkincarePriceTier = "budget" | "mid-range" | "premium";

export type SkincareProduct = {
  id: string;
  name: string;
  brand: string;
  productType: SkincareProductType;
  skinTypes: string[];
  goals: string[];
  avoidFor: string[];
  priceTier: SkincarePriceTier;
  imageUrl: string;
  productUrl: string;
  affiliateSource: string;
  tags: string[];
};

const e = {
  imageUrl: "",
  affiliateSource: "",
} as const;

/** Retailer search URLs — stable when PDP paths or ASINs change. */
function productSearchQuery(brand: string, name: string): string {
  return `${brand} ${name}`.trim();
}

function amazonProductSearch(query: string): string {
  return `https://www.amazon.com/s?k=${encodeURIComponent(query)}`;
}

function sephoraProductSearch(query: string): string {
  return `https://www.sephora.com/search?keyword=${encodeURIComponent(query)}`;
}

function ultaProductSearch(query: string): string {
  return `https://www.ulta.com/search?search=${encodeURIComponent(query)}`;
}

function iherbProductSearch(query: string): string {
  return `https://www.iherb.com/search?kw=${encodeURIComponent(query)}`;
}

/** Product rows may use retailer search URLs or direct affiliate PDP links — expand carefully to avoid duplicates. */
export const skincareProducts: SkincareProduct[] = [
  // --- 25 moisturizers ---
  { id: "cerave-moisturizing-cream", name: "Moisturizing Cream", brand: "CeraVe", productType: "moisturizer", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/3QL8r5n", ...e, affiliateSource: "amazon", imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products-v4/moisturizing-cream/cerave_moisturizing_cream_16oz_jar_front-700x700-v3.jpg?rev=7e37e9cc45754615b1532d77df5a0b52", tags: ["ceramides", "fragrance-free", "mve"] },
  { id: "cerave-daily-moisturizing-lotion", name: "Daily Moisturizing Lotion", brand: "CeraVe", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("CeraVe", "Daily Moisturizing Lotion")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products-v3/daily-moisturizing-lotion/700x700/cerave_daily_moisturizing_lotion_12oz_front_-700x700-v2.jpg?rev=5fb61e1db7fe49fb9faf308c5f583d65", tags: ["ceramides", "lightweight", "fragrance-free"] },
  { id: "vanicream-moisturizing-cream", name: "Moisturizing Cream", brand: "Vanicream", productType: "moisturizer", skinTypes: ["sensitive", "dry"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/3QD3JGW", ...e, affiliateSource: "amazon", imageUrl: "https://www.vanicream.com/dynamic-media/product/images/pump-tc22o-front.jpg?gravity=center&v=galleryMedia&k=u7YL8TUlAAq9Xaxn0U4ApA", tags: ["minimal-ingredients", "eczema-friendly"] },
  { id: "neutrogena-hydro-boost-water-gel", name: "Hydro Boost Water Gel", brand: "Neutrogena", productType: "moisturizer", skinTypes: ["oily", "combination", "normal"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4ui3PSO", ...e, affiliateSource: "amazon", imageUrl: "https://images.ctfassets.net/bcjr30vxh6td/3TfmeqVtWAAtF8LobCI3ss/d8071f4fa4a443a928cc00b98c84de95/NTG_USA_US_70501110478_681104748_HB_Hyaluronic_Acid_Water_Gel_Signature_1p7oz_00000.webp?w=800", tags: ["hyaluronic-acid", "gel"] },
  { id: "larocheposay-toleriane-double-repair", name: "Toleriane Double Repair Face Moisturizer", brand: "La Roche-Posay", productType: "moisturizer", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("La Roche-Posay", "Toleriane Double Repair Face Moisturizer")), ...e, imageUrl: "https://media.ulta.com/i/ulta/2509730", tags: ["ceramides", "niacinamide", "fragrance-free"] },
  { id: "first-aid-beauty-ultra-repair-cream", name: "Ultra Repair Cream", brand: "First Aid Beauty", productType: "moisturizer", skinTypes: ["dry", "sensitive"], goals: ["barrier repair", "soothing"], avoidFor: ["eucalyptus-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4vOBRim", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2935625-main-zoom.jpg", tags: ["colloidal-oatmeal", "rich"] },
  { id: "kiehls-ultra-facial-cream", name: "Ultra Facial Cream with Squalane", brand: "Kiehl's", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4uHbY2V", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2663763-main-zoom.jpg", tags: ["squalane", "glacial-glycoprotein"] },
  { id: "weleda-skin-food-original", name: "Skin Food Original Ultra-Rich Cream", brand: "Weleda", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["barrier repair"], avoidFor: ["essential-oil-sensitive", "fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/49sm3J9", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["botanicals", "rich"] },
  { id: "eucerin-advanced-repair-cream", name: "Advanced Repair Cream", brand: "Eucerin", productType: "moisturizer", skinTypes: ["dry", "very-dry"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4cP7PEA", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["urea", "ceramide"] },
  { id: "aveeno-calm-restore-oat-gel", name: "Calm + Restore Oat Gel Moisturizer", brand: "Aveeno", productType: "moisturizer", skinTypes: ["sensitive", "dry"], goals: ["soothing", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/3QDgcKL", ...e, affiliateSource: "amazon", imageUrl: "https://images.ctfassets.net/mgaihfszrtka/6K6lC4Dwg64DAbYjnlDTph/57ce9c4af1f7e96da2a6888737f4c070/7oz_oobwb-min-en-us-Aveeno?fm=webp&w=800", tags: ["oat", "fragrance-free"] },
  { id: "peter-thomas-roth-water-drench", name: "Water Drench Hyaluronic Cloud Cream", brand: "Peter Thomas Roth", productType: "moisturizer", skinTypes: ["combination", "oily", "normal"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4emsVJH", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s1898550-main-zoom.jpg", tags: ["hyaluronic-acid", "gel-cream"] },
  { id: "drunk-elephant-protini", name: "Protini Polypeptide Cream", brand: "Drunk Elephant", productType: "moisturizer", skinTypes: ["normal", "combination", "dry"], goals: ["anti-aging", "hydration"], avoidFor: [], priceTier: "premium", productUrl: "https://amzn.to/4eoMdy6", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2025633-main-zoom.jpg", tags: ["peptides", "amino-acids"] },
  { id: "tatcha-the-water-cream", name: "The Water Cream", brand: "Tatcha", productType: "moisturizer", skinTypes: ["oily", "combination", "normal"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/3QphB7R", ...e, affiliateSource: "amazon", imageUrl: "https://media.ulta.com/i/ulta/2634101", tags: ["japanese-leopard-lily", "oil-free"] },
  { id: "clinique-ddmg", name: "Dramatically Different Moisturizing Gel", brand: "Clinique", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4eolyl9", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s789727-main-zoom.jpg", tags: ["oil-free", "gel"] },
  { id: "origins-ginzing-gel", name: "GinZing Energy-Boosting Gel Moisturizer", brand: "Origins", productType: "moisturizer", skinTypes: ["normal", "combination"], goals: ["hydration", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4osuoTz", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["caffeine", "ginseng"] },
  { id: "embryolisse-lait-creme-concentre", name: "Lait-Crème Concentré", brand: "Embryolisse", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4uyOoVW", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["multi-use", "makeup-primer"] },
  { id: "nivea-creme", name: "Creme", brand: "Nivea", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["barrier repair"], avoidFor: ["fragrance-sensitive", "fungal-acne-prone"], priceTier: "budget", productUrl: "https://amzn.to/4d0XCn0", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["petrolatum-rich", "classic"] },
  { id: "stratia-liquid-gold", name: "Liquid Gold", brand: "Stratia", productType: "moisturizer", skinTypes: ["dry", "sensitive", "barrier-damaged"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4tYAsoL", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["ceramides", "cholesterol", "fatty-acids"] },
  { id: "paulas-choice-omega-complex-moisturizer", name: "Omega+ Complex Moisturizer", brand: "Paula's Choice", productType: "moisturizer", skinTypes: ["dry", "normal", "sensitive"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4w8oiLp", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["omega-oils", "ceramides"] },
  { id: "belif-aqua-bomb", name: "The True Cream Aqua Bomb", brand: "belif", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/3QCSVc5", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["gel-cream", "cooling"] },
  { id: "it-cosmetics-confidence-cream", name: "Confidence in a Cream Hydrating Moisturizer", brand: "IT Cosmetics", productType: "moisturizer", skinTypes: ["dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("IT Cosmetics", "Confidence in a Cream Hydrating Moisturizer")), ...e, imageUrl: "", tags: ["collagen", "peptides"] },
  { id: "yttp-superfood-air-whip", name: "Superfood Air-Whip Moisture Cream", brand: "Youth To The People", productType: "moisturizer", skinTypes: ["combination", "normal"], goals: ["hydration"], avoidFor: ["essential-oil-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4vOH2Pc", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["kale", "spinach", "hyaluronic-acid"] },
  { id: "glow-recipe-plum-plump-cream", name: "Plum Plump Hyaluronic Cream", brand: "Glow Recipe", productType: "moisturizer", skinTypes: ["normal", "combination", "dry"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Glow Recipe", "Plum Plump Hyaluronic Cream")), ...e, imageUrl: "", tags: ["plum", "hyaluronic-acid"] },
  { id: "summer-fridays-cloud-dew", name: "Cloud Dew Oil-Free Gel Cream Moisturizer", brand: "Summer Fridays", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Summer Fridays", "Cloud Dew Oil-Free Gel Cream Moisturizer")), ...e, imageUrl: "", tags: ["oil-free", "amino-acids"] },
  { id: "olay-regenerist-micro-sculpting-cream", name: "Regenerist Micro-Sculpting Cream", brand: "Olay", productType: "moisturizer", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/3OIZoBs", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["niacinamide", "peptides"] },

  // --- 20 sunscreens ---
  { id: "eltamd-uv-clear-spf46", name: "UV Clear Broad-Spectrum SPF 46", brand: "EltaMD", productType: "sunscreen", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["oil-control", "sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/42w1mZf", ...e, affiliateSource: "amazon", imageUrl: "https://eltamd.com/cdn/shop/files/UV_Clear_SPF_46_02500A_With_award_1200x1200.jpg?v=1773888112", tags: ["mineral-leaning", "niacinamide", "dermatologist-favorite"] },
  { id: "larocheposay-anthelios-melt-in-milk-spf60", name: "Anthelios Melt-in Milk Sunscreen SPF 60", brand: "La Roche-Posay", productType: "sunscreen", skinTypes: ["normal", "dry", "sensitive"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/3QNToYD", ...e, affiliateSource: "amazon", imageUrl: "https://media.ulta.com/i/ulta/2236414", tags: ["broad-spectrum", "water-resistant"] },
  { id: "supergoop-unseen-sunscreen-spf40", name: "Unseen Sunscreen SPF 40", brand: "Supergoop", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: ["silicone-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Supergoop", "Unseen Sunscreen SPF 40")), ...e, imageUrl: "https://cdn.shopify.com/s/files/1/1503/5658/files/Unseen_PDP_1180x1604_5d03ff64-0ed3-4fbb-8bef-c6b7dfbaa0bd.png?v=1774797043", tags: ["chemical", "primer-feel"] },
  { id: "cerave-hydrating-mineral-spf30", name: "Hydrating Mineral Sunscreen SPF 30", brand: "CeraVe", productType: "sunscreen", skinTypes: ["sensitive", "dry", "normal"], goals: ["sun protection", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/42fqwLp", ...e, affiliateSource: "amazon", imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/sunscreen/face/30-spf-face/30-spf-face_front.jpg?rev=3a662171cf3d47eea33f18a9d080b1a8", tags: ["mineral", "ceramides"] },
  { id: "neutrogena-ultra-sheer-spf55", name: "Ultra Sheer Dry-Touch Sunscreen SPF 55", brand: "Neutrogena", productType: "sunscreen", skinTypes: ["normal", "oily", "combination"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/48BXyca", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["chemical", "dry-touch"] },
  { id: "australian-gold-botanical-tinted-spf50", name: "Botanical Tinted Face Sunscreen SPF 50", brand: "Australian Gold", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Australian Gold", "Botanical Tinted Face Sunscreen SPF 50")), ...e, imageUrl: "", tags: ["mineral", "tinted"] },
  { id: "isdin-eryfotona-actinica-spf50", name: "Eryfotona Actinica Mineral Sunscreen SPF 50+", brand: "ISDIN", productType: "sunscreen", skinTypes: ["normal", "dry", "mature"], goals: ["sun protection", "anti-aging"], avoidFor: [], priceTier: "premium", productUrl: "https://amzn.to/3QYDhaI", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["mineral", "dna-repairosomes"] },
  { id: "blue-lizard-sensitive-mineral-spf50", name: "Sensitive Mineral Sunscreen SPF 50+", brand: "Blue Lizard", productType: "sunscreen", skinTypes: ["sensitive", "children"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4uofBLl", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["mineral", "reef-conscious-line"] },
  { id: "cosrx-aloe-soothing-sun-cream-spf50", name: "Aloe Soothing Sun Cream SPF 50 PA+++", brand: "COSRX", productType: "sunscreen", skinTypes: ["dry", "sensitive", "normal"], goals: ["sun protection", "soothing"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("COSRX", "Aloe Soothing Sun Cream SPF 50 PA+++")), ...e, imageUrl: "", tags: ["chemical", "aloe"] },
  { id: "beauty-of-joseon-relief-sun-spf50", name: "Relief Sun Rice + Probiotics SPF 50+ PA++++", brand: "Beauty of Joseon", productType: "sunscreen", skinTypes: ["normal", "dry", "sensitive"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Beauty of Joseon", "Relief Sun Rice + Probiotics SPF 50+ PA++++")), ...e, imageUrl: "", tags: ["chemical", "rice"] },
  { id: "skin-aqua-tone-up-uv-essence", name: "Tone Up UV Essence SPF 50+ PA++++", brand: "Skin Aqua", productType: "sunscreen", skinTypes: ["normal", "combination"], goals: ["sun protection", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Skin Aqua", "Tone Up UV Essence SPF 50+ PA++++")), ...e, imageUrl: "", tags: ["japanese", "tone-up"] },
  { id: "canmake-mermaid-skin-gel-uv", name: "Mermaid Skin Gel UV SPF 50+ PA++++", brand: "Canmake", productType: "sunscreen", skinTypes: ["normal", "oily", "combination"], goals: ["sun protection"], avoidFor: ["alcohol-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Canmake", "Mermaid Skin Gel UV SPF 50+ PA++++")), ...e, imageUrl: "", tags: ["gel", "japanese"] },
  { id: "black-girl-sunscreen-spf30", name: "Make Me Invisible SPF 30", brand: "Black Girl Sunscreen", productType: "sunscreen", skinTypes: ["all", "deeper-skin-tones"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Black Girl Sunscreen", "Make Me Invisible SPF 30")), ...e, imageUrl: "", tags: ["no-white-cast-focus", "broad-spectrum"] },
  { id: "shiseido-ultimate-sun-protector-spf50", name: "Ultimate Sun Protector Cream SPF 50+ WetForce", brand: "Shiseido", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Shiseido", "Ultimate Sun Protector Cream SPF 50+ WetForce")), ...e, imageUrl: "", tags: ["wetforce", "synchroshield"] },
  { id: "drunk-elephant-umbra-sheer-spf30", name: "Umbra Sheer Physical Daily Defense SPF 30", brand: "Drunk Elephant", productType: "sunscreen", skinTypes: ["sensitive", "normal"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Drunk Elephant", "Umbra Sheer Physical Daily Defense SPF 30")), ...e, imageUrl: "", tags: ["mineral", "marula"] },
  { id: "biossance-squalane-zinc-spf30", name: "Squalane + Zinc Sheer Mineral Sunscreen SPF 30 PA +++", brand: "Biossance", productType: "sunscreen", skinTypes: ["sensitive", "dry", "normal"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Biossance", "Squalane + Zinc Sheer Mineral Sunscreen SPF 30 PA +++")), ...e, imageUrl: "", tags: ["mineral", "squalane"] },
  { id: "sun-bum-original-spf50", name: "Original SPF 50 Sunscreen Lotion", brand: "Sun Bum", productType: "sunscreen", skinTypes: ["normal", "body"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4weh9cL", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["coconut-scent", "broad-spectrum"] },
  { id: "aveeno-protect-hydrate-spf60", name: "Protect + Hydrate Sunscreen Broad Spectrum SPF 60", brand: "Aveeno", productType: "sunscreen", skinTypes: ["dry", "normal"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/42KHYri", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["oat", "chemical"] },
  { id: "paulas-choice-youth-extending-fluid-spf50", name: "Youth-Extending Daily Hydrating Fluid SPF 50", brand: "Paula's Choice", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Paula's Choice", "Youth-Extending Daily Hydrating Fluid SPF 50")), ...e, imageUrl: "", tags: ["antioxidants", "fluid"] },
  { id: "tower28-sunnydays-spf30", name: "SunnyDays SPF 30 Tinted Sunscreen Foundation", brand: "Tower 28", productType: "sunscreen", skinTypes: ["sensitive", "normal", "combination"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Tower 28", "SunnyDays SPF 30 Tinted Sunscreen Foundation")), ...e, imageUrl: "", tags: ["tinted", "national-eczema-association-seal"] },

  // --- 20 serums ---
  { id: "the-ordinary-niacinamide-zinc", name: "Niacinamide 10% + Zinc 1%", brand: "The Ordinary", productType: "serum", skinTypes: ["oily", "acne-prone", "combination"], goals: ["oil-control", "pore appearance"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/3SGhqWh", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2031391-main-zoom.jpg", tags: ["niacinamide", "zinc"] },
  { id: "skinceuticals-ce-ferulic", name: "C E Ferulic", brand: "SkinCeuticals", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "brightening"], avoidFor: ["vitamin-c-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4uDkobD", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["vitamin-c", "vitamin-e", "ferulic-acid"] },
  { id: "drunk-elephant-tlc-framboos", name: "T.L.C. Framboos Glycolic Resurfacing Night Serum", brand: "Drunk Elephant", productType: "serum", skinTypes: ["normal", "combination", "oily"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Drunk Elephant", "T.L.C. Framboos Glycolic Resurfacing Night Serum")), ...e, imageUrl: "", tags: ["aha", "bha", "blend"] },
  { id: "esteelauder-advanced-night-repair", name: "Advanced Night Repair Synchronized Multi-Recovery Complex", brand: "Estée Lauder", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4fKF2mr", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["hyaluronic-acid", "bifida"] },
  { id: "lancome-genifique", name: "Advanced Génifique Youth Activating Serum", brand: "Lancôme", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4vcpyMU", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["prebiotic", "hyaluronic-acid"] },
  { id: "olay-regenerist-micro-sculpting-serum", name: "Regenerist Micro-Sculpting Serum", brand: "Olay", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/3QL2FAU", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["niacinamide", "peptides"] },
  { id: "the-ordinary-ha-b5", name: "Hyaluronic Acid 2% + B5", brand: "The Ordinary", productType: "serum", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/49WaQkC", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2735140-main-zoom.jpg", tags: ["hyaluronic-acid", "panthenol"] },
  { id: "paulas-choice-azelaic-acid-booster", name: "10% Azelaic Acid Booster", brand: "Paula's Choice", productType: "serum", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["brightening", "texture"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Paula's Choice", "10% Azelaic Acid Booster")), ...e, imageUrl: "", tags: ["azelaic-acid", "salicylic-acid"] },
  { id: "good-molecules-niacinamide-serum", name: "Niacinamide Serum", brand: "Good Molecules", productType: "serum", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "brightening"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Good Molecules", "Niacinamide Serum")), ...e, imageUrl: "", tags: ["niacinamide"] },
  { id: "vichy-mineral-89", name: "Minéral 89 Hyaluronic Acid Face Serum", brand: "Vichy", productType: "serum", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/3QDhC83", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["volcanic-water", "hyaluronic-acid"] },
  { id: "kiehls-midnight-recovery", name: "Midnight Recovery Concentrate Face Oil", brand: "Kiehl's", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["essential-oil-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/43wf3Yz", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s1988732-main-zoom.jpg", tags: ["evening-primrose", "lavender-oil"] },
  { id: "biossance-vitamin-c-dark-spot", name: "Squalane + Vitamin C Dark Spot Serum", brand: "Biossance", productType: "serum", skinTypes: ["normal", "combination", "dry"], goals: ["brightening", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Biossance", "Squalane + Vitamin C Dark Spot Serum")), ...e, imageUrl: "", tags: ["vitamin-c-derivative", "squalane"] },
  { id: "sunday-riley-good-genes", name: "Good Genes All-In-One Lactic Acid Treatment", brand: "Sunday Riley", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "premium", productUrl: "https://amzn.to/3SHaXKL", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["lactic-acid"] },
  { id: "larocheposay-pure-vitamin-c10", name: "Pure Vitamin C10 Serum", brand: "La Roche-Posay", productType: "serum", skinTypes: ["normal", "combination"], goals: ["brightening"], avoidFor: ["vitamin-c-sensitive"], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("La Roche-Posay", "Pure Vitamin C10 Serum")), ...e, imageUrl: "", tags: ["vitamin-c", "salicylic-acid"] },
  { id: "versed-press-restart-retinol", name: "Press Restart Gentle Retinol Serum", brand: "Versed", productType: "serum", skinTypes: ["normal", "combination", "mature"], goals: ["anti-aging", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Versed", "Press Restart Gentle Retinol Serum")), ...e, imageUrl: "", tags: ["retinol", "bakuchiol"] },
  { id: "glow-recipe-watermelon-dew-drops", name: "Watermelon Glow Niacinamide Dew Drops", brand: "Glow Recipe", productType: "serum", skinTypes: ["normal", "dry", "combination"], goals: ["brightening", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4vTlKAa", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["niacinamide", "highlight"] },
  { id: "innisfree-green-tea-seed-serum", name: "Green Tea Seed Hyaluronic Serum", brand: "innisfree", productType: "serum", skinTypes: ["normal", "combination", "dry"], goals: ["hydration", "antioxidant"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4cMMifF", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["green-tea", "hyaluronic-acid"] },
  { id: "sulwhasoo-first-care-activating-serum", name: "First Care Activating Serum VI", brand: "Sulwhasoo", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4xyxLfW", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["hanbang", "jaum"] },
  { id: "lancome-genifique-light-pearl", name: "Advanced Génifique Yeux Light-Pearl Eye & Lash Serum", brand: "Lancôme", productType: "serum", skinTypes: ["normal", "mature"], goals: ["anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4fLGwg5", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["eye", "lash"] },
  { id: "the-ordinary-buffet-copper", name: "Buffet + Copper Peptides 1%", brand: "The Ordinary", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging"], avoidFor: ["vitamin-c-stacking"], priceTier: "budget", productUrl: "https://amzn.to/3QGUDco", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["peptides", "copper"] },

  // --- 15 cleansers ---
  { id: "cerave-hydrating-cleanser", name: "Hydrating Facial Cleanser", brand: "CeraVe", productType: "cleanser", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("CeraVe", "Hydrating Facial Cleanser")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/cleansers/hydrating-facial-cleanser/photos/2022/700x700/cerave_daily_hydrating-cleanser_12oz_front-700x700-v2.jpg?rev=8dcf681b75c042deaaa0c6ea1581d4df", tags: ["ceramides", "non-foaming"] },
  { id: "cerave-foaming-cleanser", name: "Foaming Facial Cleanser", brand: "CeraVe", productType: "cleanser", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("CeraVe", "Foaming Facial Cleanser")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products-v3/foaming-facial-cleanser/700x700/cerave_foaming-facial-cleanser-12oz_front-700x700-v2.jpg?rev=da10428fc5104c97a980e0d5ff5ce9bb", tags: ["niacinamide", "ceramides"] },
  { id: "larocheposay-toleriane-gentle-cleanser", name: "Toleriane Hydrating Gentle Cleanser", brand: "La Roche-Posay", productType: "cleanser", skinTypes: ["dry", "sensitive"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("La Roche-Posay", "Toleriane Hydrating Gentle Cleanser")), ...e, imageUrl: "", tags: ["cream", "fragrance-free"] },
  { id: "vanicream-gentle-facial-cleanser", name: "Gentle Facial Cleanser", brand: "Vanicream", productType: "cleanser", skinTypes: ["sensitive", "dry"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/42GzLEy", ...e, affiliateSource: "amazon", imageUrl: "https://www.vanicream.com/dynamic-media/product/images/gentle-facial-cleanser-8-oz-front.jpg?gravity=center&v=galleryMedia&k=wpsSDw6D4yetnnA15I28ig", tags: ["minimal", "gluten-free"] },
  { id: "fresh-soy-face-cleanser", name: "Soy Face Cleanser", brand: "Fresh", productType: "cleanser", skinTypes: ["normal", "dry", "sensitive"], goals: ["gentle-cleanse", "hydration"], avoidFor: ["soy-allergy"], priceTier: "mid-range", productUrl: "https://amzn.to/3SHbrk3", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["soy", "amino-acids"] },
  { id: "yttp-superfood-cleanser", name: "Superfood Antioxidant Cleanser", brand: "Youth To The People", productType: "cleanser", skinTypes: ["normal", "combination", "oily"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Youth To The People", "Superfood Antioxidant Cleanser")), ...e, imageUrl: "", tags: ["kale", "spinach", "gel"] },
  { id: "neutrogena-fresh-foaming-cleanser", name: "Fresh Foaming Cleanser", brand: "Neutrogena", productType: "cleanser", skinTypes: ["normal", "combination"], goals: ["makeup-removal"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/48CHtTJ", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["foaming"] },
  { id: "cosrx-low-ph-good-morning", name: "Low pH Good Morning Gel Cleanser", brand: "COSRX", productType: "cleanser", skinTypes: ["oily", "combination", "acne-prone"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("COSRX", "Low pH Good Morning Gel Cleanser")), ...e, imageUrl: "", tags: ["low-ph", "bha"] },
  { id: "krave-matcha-hemp-cleanser", name: "Matcha Hemp Hydrating Cleanser", brand: "Krave Beauty", productType: "cleanser", skinTypes: ["normal", "dry", "combination"], goals: ["hydration", "gentle-cleanse"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/3P5jFB4", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["matcha", "hemp"] },
  { id: "paulas-choice-resist-hydrating-cleanser", name: "RESIST Optimal Results Hydrating Cleanser", brand: "Paula's Choice", productType: "cleanser", skinTypes: ["dry", "normal", "sensitive"], goals: ["gentle-cleanse", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/3P5jNk2", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["cream", "antioxidants"] },
  { id: "kiehls-ultra-facial-cleanser", name: "Ultra Facial Cleanser", brand: "Kiehl's", productType: "cleanser", skinTypes: ["normal", "combination", "dry"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4a3Eg0a", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["squalane", "apricot-kernel"] },
  { id: "glossier-milky-jelly-cleanser", name: "Milky Jelly Cleanser", brand: "Glossier", productType: "cleanser", skinTypes: ["normal", "dry", "sensitive"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Glossier", "Milky Jelly Cleanser")), ...e, imageUrl: "", tags: ["allantoin", "pro-vitamin-b5"] },
  { id: "innisfree-green-tea-foam-cleanser", name: "Green Tea Hyaluronic Acid Hydrating Foam Cleanser", brand: "innisfree", productType: "cleanser", skinTypes: ["normal", "combination", "oily"], goals: ["hydration", "gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4uyIkN2", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["green-tea", "foam"] },
  { id: "dhc-deep-cleansing-oil", name: "Deep Cleansing Oil", brand: "DHC", productType: "cleanser", skinTypes: ["dry", "normal", "combination"], goals: ["makeup-removal"], avoidFor: ["olive-oil-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/42JJ3Q5", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["oil-cleanser", "double-cleanse"] },
  { id: "tatcha-rice-wash", name: "The Rice Wash Skin-Softening Cleanser", brand: "Tatcha", productType: "cleanser", skinTypes: ["normal", "dry", "combination"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4oupENk", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["rice", "ph-neutral"] },

  // --- 10 toners / essences ---
  { id: "laneige-cream-skin-refiner", name: "Cream Skin Cerapeptide™ Toner & Moisturizer", brand: "Laneige", productType: "toner", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/44apGjU", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["ceramide", "milky-toner"] },
  { id: "cosrx-snail-96-essence", name: "Advanced Snail 96 Mucin Power Essence", brand: "COSRX", productType: "toner", skinTypes: ["dry", "normal", "sensitive"], goals: ["hydration", "barrier repair"], avoidFor: ["snail-allergy"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("COSRX", "Advanced Snail 96 Mucin Power Essence")), ...e, imageUrl: "", tags: ["snail-mucin", "essence"] },
  { id: "missha-time-revolution-essence-5x", name: "Time Revolution The First Essence 5X", brand: "Missha", productType: "toner", skinTypes: ["normal", "dry", "mature"], goals: ["hydration", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/3SllRG9", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["fermented", "first-essence"] },
  { id: "sk-ii-facial-treatment-essence", name: "Facial Treatment Essence", brand: "SK-II", productType: "toner", skinTypes: ["normal", "combination", "mature"], goals: ["texture", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4uwWNcF", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["pitera", "fermented"] },
  { id: "paulas-choice-2-bha-liquid", name: "Skin Perfecting 2% BHA Liquid Exfoliant", brand: "Paula's Choice", productType: "toner", skinTypes: ["oily", "acne-prone", "combination"], goals: ["texture", "pores"], avoidFor: ["pregnancy", "sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4eiK1K1", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2421360-main-zoom.jpg", tags: ["salicylic-acid", "leave-on"] },
  { id: "pyunkang-yul-essence-toner", name: "Essence Toner", brand: "Pyunkang Yul", productType: "toner", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4tJcr4Z", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["minimal", "astringent-free"] },
  { id: "thayers-alcohol-free-toner", name: "Alcohol-Free Witch Hazel Facial Toner", brand: "Thayers", productType: "toner", skinTypes: ["normal", "combination", "oily"], goals: ["oil-control"], avoidFor: ["witch-hazel-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4cP9SIM", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["witch-hazel", "aloe"] },
  { id: "dickinsons-enhanced-witch-hazel-toner", name: "Enhanced Witch Hazel Hydrating Toner", brand: "Dickinson's", productType: "toner", skinTypes: ["normal", "combination"], goals: ["hydration"], avoidFor: ["witch-hazel-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Dickinson's", "Enhanced Witch Hazel Hydrating Toner")), ...e, imageUrl: "", tags: ["witch-hazel", "hyaluronic-acid"] },
  { id: "hada-labo-gokujyun-lotion-moist", name: "Gokujyun Hyaluronic Acid Lotion (Moist)", brand: "Hada Labo", productType: "toner", skinTypes: ["dry", "normal"], goals: ["hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4n5H5D3", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["hyaluronic-acid", "japanese"] },
  { id: "mario-badescu-glycolic-acid-toner", name: "Glycolic Acid Toner", brand: "Mario Badescu", productType: "toner", skinTypes: ["normal", "oily", "combination"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Mario Badescu", "Glycolic Acid Toner")), ...e, imageUrl: "", tags: ["glycolic-acid"] },

  // --- 15 acne treatments ---
  { id: "differin-adapalene-gel", name: "Adapalene Gel 0.1%", brand: "Differin", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Differin", "Adapalene Gel 0.1%")), ...e, imageUrl: "", tags: ["retinoid", "otc"] },
  { id: "larocheposay-effaclar-duo", name: "Effaclar Duo (+) Acne Treatment", brand: "La Roche-Posay", productType: "acne treatment", skinTypes: ["acne-prone", "oily", "combination"], goals: ["acne"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/3RgMSK4", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s1402668-main-zoom.jpg", tags: ["niacinamide", "texture"] },
  { id: "paulas-choice-clear-bp-treatment", name: "Clear Regular Strength Daily Skin Clearing Treatment 2.5% Benzoyl Peroxide", brand: "Paula's Choice", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy", "benzoyl-peroxide-allergy"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Paula's Choice", "Clear Regular Strength Daily Skin Clearing Treatment 2.5% Benzoyl Peroxide")), ...e, imageUrl: "", tags: ["benzoyl-peroxide"] },
  { id: "mario-badescu-drying-lotion", name: "Drying Lotion", brand: "Mario Badescu", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["sensitive", "fragrance-sensitive"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Mario Badescu", "Drying Lotion")), ...e, imageUrl: "", tags: ["spot", "sulfur-calamine"] },
  { id: "neutrogena-rapid-clear-stubborn-acne", name: "Rapid Clear Stubborn Acne Spot Gel", brand: "Neutrogena", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["pregnancy"], priceTier: "budget", productUrl: "https://amzn.to/4tR2dzF", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["benzoyl-peroxide", "spot"] },
  { id: "the-ordinary-salicylic-acid-2", name: "Salicylic Acid 2% Solution", brand: "The Ordinary", productType: "acne treatment", skinTypes: ["oily", "acne-prone"], goals: ["acne", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4xyurS4", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["salicylic-acid"] },
  { id: "acnefree-terminator-10", name: "Terminator 10 Maximum Strength Acne Spot Treatment", brand: "AcneFree", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["benzoyl-peroxide-allergy"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("AcneFree", "Terminator 10 Maximum Strength Acne Spot Treatment")), ...e, imageUrl: "", tags: ["benzoyl-peroxide", "10-percent"] },
  { id: "kate-somerville-eradikate", name: "EradiKate Acne Treatment", brand: "Kate Somerville", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["sulfur-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Kate Somerville", "EradiKate Acne Treatment")), ...e, imageUrl: "", tags: ["sulfur", "spot"] },
  { id: "peace-out-acne-dots", name: "Acne Healing Dots", brand: "Peace Out", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["hydrocolloid-allergy"], priceTier: "mid-range", productUrl: "https://amzn.to/4v5tP4w", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["hydrocolloid", "salicylic-acid"] },
  { id: "hero-mighty-patch-original", name: "Mighty Patch Original", brand: "Hero Cosmetics", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/3QIAoec", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["hydrocolloid", "overnight"] },
  { id: "murad-outsmart-acne", name: "Outsmart Acne Clarifying Treatment", brand: "Murad", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne", "oil-control"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Murad", "Outsmart Acne Clarifying Treatment")), ...e, imageUrl: "", tags: ["salicylic-acid", "glycolic-acid"] },
  { id: "clinique-acne-solutions-clinical-gel", name: "Acne Solutions Clinical Clearing Gel", brand: "Clinique", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("Clinique", "Acne Solutions Clinical Clearing Gel")), ...e, imageUrl: "", tags: ["salicylic-acid"] },
  { id: "origins-super-spot-remover", name: "Super Spot Remover Blemish Treatment Gel", brand: "Origins", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Origins", "Super Spot Remover Blemish Treatment Gel")), ...e, imageUrl: "", tags: ["salicylic-acid", "spot"] },
  { id: "panoxyl-acne-foaming-wash-10", name: "Acne Foaming Wash Benzoyl Peroxide 10% Maximum Strength", brand: "PanOxyl", productType: "acne treatment", skinTypes: ["acne-prone", "oily", "body"], goals: ["acne"], avoidFor: ["sensitive", "dry"], priceTier: "budget", productUrl: "https://amzn.to/4tKd667", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["benzoyl-peroxide", "cleanser"] },
  { id: "larocheposay-effaclar-medicated-wash", name: "Effaclar Medicated Acne Face Wash", brand: "La Roche-Posay", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("La Roche-Posay", "Effaclar Medicated Acne Face Wash")), ...e, imageUrl: "", tags: ["salicylic-acid", "2-percent"] },

  // --- 15 barrier repair ---
  { id: "cerave-healing-ointment", name: "Healing Ointment", brand: "CeraVe", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair"], avoidFor: ["petrolatum-averse"], priceTier: "budget", productUrl: "https://amzn.to/4eIqSBR", ...e, affiliateSource: "amazon", imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/moisturizers/healing-ointment/2025/healing-ointment_front.jpg?rev=c41d50fa05b34fa59e5affe3b389b681", tags: ["petrolatum", "ceramides"] },
  { id: "aquaphor-healing-ointment", name: "Healing Ointment", brand: "Aquaphor", productType: "barrier repair", skinTypes: ["dry", "sensitive", "lips"], goals: ["barrier repair"], avoidFor: ["lanolin-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Aquaphor", "Healing Ointment")), ...e, imageUrl: "", tags: ["petrolatum", "multi-use"] },
  { id: "eucerin-eczema-relief-cream", name: "Eczema Relief Body Cream", brand: "Eucerin", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/3QNVY0L", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["colloidal-oatmeal", "ceramide"] },
  { id: "first-aid-beauty-ultra-repair-ointment", name: "Ultra Repair Ointment", brand: "First Aid Beauty", productType: "barrier repair", skinTypes: ["dry", "sensitive"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4tOabcR", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["petrolatum", "colloidal-oatmeal"] },
  { id: "larocheposay-cicaplast-baume-b5", name: "Cicaplast Baume B5", brand: "La Roche-Posay", productType: "barrier repair", skinTypes: ["dry", "sensitive", "irritated"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4cMt7CC", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["panthenol", "madecassoside"] },
  { id: "avene-cicalfate-plus", name: "Cicalfate+ Restorative Protective Cream", brand: "Avène", productType: "barrier repair", skinTypes: ["sensitive", "dry", "post-procedure"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4w6KMfL", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["zinc", "copper"] },
  { id: "skinfix-barrier-lipid-peptide-cream", name: "Barrier+ Triple Lipid-Peptide Face Cream", brand: "Skinfix", productType: "barrier repair", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4v5u2EQ", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["lipids", "peptides"] },
  { id: "drjart-ceramidin-cream", name: "Ceramidin™ Skin Barrier Moisturizing Cream", brand: "Dr. Jart+", productType: "barrier repair", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/3QokqGe", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["ceramide", "panthenol"] },
  { id: "krave-great-barrier-relief", name: "Great Barrier Relief", brand: "Krave Beauty", productType: "barrier repair", skinTypes: ["sensitive", "dry", "combination"], goals: ["barrier repair", "soothing"], avoidFor: ["tamanu-sensitive"], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Krave Beauty", "Great Barrier Relief")), ...e, imageUrl: "", tags: ["tamanu", "ceramide"] },
  { id: "biossance-omega-repair-cream", name: "Squalane + Omega Repair Deep Hydration Moisturizer", brand: "Biossance", productType: "barrier repair", skinTypes: ["dry", "normal", "mature"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4orWaQ1", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["omega-fatty-acids", "squalane"] },
  { id: "elizabeth-arden-eight-hour-cream", name: "Eight Hour® Cream Skin Protectant", brand: "Elizabeth Arden", productType: "barrier repair", skinTypes: ["dry", "normal", "lips"], goals: ["barrier repair"], avoidFor: ["fragrance-sensitive", "lanolin-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/42JmhI3", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["petrolatum", "classic"] },
  { id: "weleda-calendula-face-cream", name: "Calendula Face Cream", brand: "Weleda", productType: "barrier repair", skinTypes: ["dry", "sensitive", "baby-safe"], goals: ["barrier repair", "soothing"], avoidFor: ["essential-oil-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4tMyXd4", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["calendula", "natural"] },
  { id: "mustela-stelatopia-emollient-cream", name: "Stelatopia Emollient Cream", brand: "Mustela", productType: "barrier repair", skinTypes: ["dry", "eczema-prone", "baby"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Mustela", "Stelatopia Emollient Cream")), ...e, imageUrl: "", tags: ["sunflower", "fragrance-free"] },
  { id: "bioderma-atoderm-intensive-balm", name: "Atoderm Intensive Balm", brand: "Bioderma", productType: "barrier repair", skinTypes: ["very-dry", "sensitive", "eczema-prone"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4eYfJg4", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["lipid-complex", "fragrance-free"] },
  { id: "larocheposay-lipikar-balm-ap-plus", name: "Lipikar Balm AP+ Intense Repair Moisturizing Body & Face Cream", brand: "La Roche-Posay", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4wbXoTa", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["ceramide", "niacinamide"] },

  // --- Amazon affiliate additions ---
  { id: "vichy-aqualia-thermal-rich-cream", name: "Aqualia Thermal Rich Cream Moisturizer", brand: "Vichy", productType: "moisturizer", skinTypes: ["dry", "normal", "sensitive"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/44ePc7z", ...e, affiliateSource: "amazon", imageUrl: "https://www.cvs.com/bizcontent/merchandising/productimages/high_res/3337875588225.jpg", tags: ["hyaluronic-acid", "volcanic-water"] },
  { id: "laneige-water-bank-blue-ha-cream", name: "Water Bank Blue HA Moisturizing Cream", brand: "Laneige", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4w7PpWd", ...e, affiliateSource: "amazon", imageUrl: "https://cdn.shopify.com/s/files/1/0255/0189/2660/files/LN_WBCM_24AD_Product_02.jpg?v=1703778486", tags: ["hyaluronic-acid", "ceramide"] },
  { id: "laneige-water-sleeping-mask", name: "Water Sleeping Mask", brand: "Laneige", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4ajtbrR", ...e, affiliateSource: "amazon", imageUrl: "https://cdn.shopify.com/s/files/1/0255/0189/2660/files/WSM_AD_PDP_2.jpg?v=1754046790", tags: ["overnight", "sleeping-mask"] },
  { id: "drunk-elephant-lala-retro", name: "Lala Retro™ Whipped Cream", brand: "Drunk Elephant", productType: "moisturizer", skinTypes: ["dry", "normal", "sensitive"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "premium", productUrl: "https://amzn.to/4gDDcUB", ...e, affiliateSource: "amazon", imageUrl: "https://media.ulta.com/i/ulta/2588438", tags: ["ceramides", "rich"] },
  { id: "tatcha-dewy-skin-cream", name: "The Dewy Skin Cream Plumping & Hydrating Moisturizer", brand: "Tatcha", productType: "moisturizer", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4uVqCDT", ...e, affiliateSource: "amazon", imageUrl: "https://media.ulta.com/i/ulta/2634098", tags: ["plumping", "rich"] },
  { id: "the-ordinary-nmf-ha", name: "Natural Moisturizing Factors + HA", brand: "The Ordinary", productType: "moisturizer", skinTypes: ["normal", "combination", "oily"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4vYMsHw", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2031392-main-zoom.jpg", tags: ["nmf", "hyaluronic-acid"] },
  { id: "murad-hydro-dynamic-ultimate-moisture", name: "Hydro-Dynamic Ultimate Moisture", brand: "Murad", productType: "moisturizer", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/44sHDdE", ...e, affiliateSource: "amazon", imageUrl: "https://media.ulta.com/i/ulta/2544836", tags: ["hyaluronic-acid", "rich"] },
  { id: "fresh-rose-deep-hydration-cream", name: "Rose Deep Hydration Face Cream", brand: "Fresh", productType: "moisturizer", skinTypes: ["dry", "normal", "sensitive"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4w16wsD", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s174401-main-zoom.jpg", tags: ["rose", "hyaluronic-acid"] },
  { id: "caudalie-vinosource-hydra-gel", name: "Vinosource-Hydra Grape Water Gel Moisturizer", brand: "Caudalie", productType: "moisturizer", skinTypes: ["normal", "combination", "oily"], goals: ["hydration", "soothing"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4gCHQ5i", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["grape-water", "gel"] },
  { id: "belif-moisturizing-bomb-mini", name: "The True Cream Moisturizing Bomb Mini", brand: "belif", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/3Qk2gFL", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2560886-main-zoom.jpg", tags: ["rich", "travel-size"] },
  { id: "laneige-bouncy-firm-sleeping-mask", name: "Bouncy & Firm Sleeping Mask Cream", brand: "Laneige", productType: "moisturizer", skinTypes: ["normal", "dry", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4w15ywv", ...e, affiliateSource: "amazon", imageUrl: "https://cdn.shopify.com/s/files/1/0255/0189/2660/files/Product_01_9129acd1-a5ce-46e2-9d30-bbd77479f839.jpg?v=1724612072", tags: ["overnight", "peptides"] },
  { id: "bioderma-sensibio-light", name: "Sensibio Light Soothing Cream", brand: "Bioderma", productType: "moisturizer", skinTypes: ["sensitive", "normal", "combination"], goals: ["soothing", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4vrbK0R", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["fragrance-free", "sensitive-skin"] },
  { id: "eucerin-roughness-relief-lotion", name: "Roughness Relief Lotion", brand: "Eucerin", productType: "moisturizer", skinTypes: ["dry", "very-dry", "rough"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/44qZ7qP", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["urea", "body-face"] },
  { id: "uriage-bariederm-cica-gel-cream", name: "Bariederm-Cica Daily Gel-Cream", brand: "Uriage", productType: "moisturizer", skinTypes: ["sensitive", "dry", "irritated"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4vugPpj", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["cica", "gel-cream"] },
  { id: "eucerin-photoaging-control-tinted-spf50", name: "Photoaging Control Tinted Facial Sun Protection SPF 50+", brand: "Eucerin", productType: "sunscreen", skinTypes: ["normal", "dry", "mature"], goals: ["sun protection", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/3ShsIAr", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["tinted", "broad-spectrum"] },
  { id: "bioderma-photoderm-max-aquafluid-spf50", name: "Photoderm MAX Aquafluid SPF 50+", brand: "Bioderma", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/3T1qZ2c", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["fluid", "broad-spectrum"] },
  { id: "laneige-radian-c-sun-cream-spf50", name: "Radian-C Sun Cream SPF 50+ PA++++", brand: "Laneige", productType: "sunscreen", skinTypes: ["normal", "combination", "dry"], goals: ["sun protection", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4oOsFbp", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["vitamin-c", "chemical"] },
  { id: "paulas-choice-niacinamide-booster", name: "10% Niacinamide Booster", brand: "Paula's Choice", productType: "serum", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "brightening"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4uROHeA", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2549343-main-zoom.jpg", tags: ["niacinamide", "booster"] },
  { id: "the-ordinary-lactic-acid-5", name: "Lactic Acid 5% + HA", brand: "The Ordinary", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "budget", productUrl: "https://amzn.to/43WJRSr", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2336469-main-zoom.jpg", tags: ["lactic-acid", "aha"] },
  { id: "the-ordinary-granactive-retinoid-2", name: "Granactive Retinoid 2% in Squalane", brand: "The Ordinary", productType: "serum", skinTypes: ["normal", "combination", "mature"], goals: ["anti-aging", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4uXomfg", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["retinoid", "squalane"] },
  { id: "sunday-riley-luna-sleeping-oil", name: "Luna Sleeping Night Oil", brand: "Sunday Riley", productType: "serum", skinTypes: ["normal", "combination", "mature"], goals: ["anti-aging", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4adVGay", ...e, affiliateSource: "amazon", imageUrl: "https://media.ulta.com/i/ulta/2550153", tags: ["retinol", "night-oil"] },
  { id: "fresh-kombucha-essence", name: "Kombucha Facial Treatment Essence", brand: "Fresh", productType: "toner", skinTypes: ["normal", "dry", "combination"], goals: ["hydration", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4uRJaEO", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2658979-main-zoom.jpg", tags: ["fermented", "essence"] },
  { id: "the-ordinary-ascorbyl-tetraisopalmitate", name: "Ascorbyl Tetraisopalmitate Solution 20% in Vitamin F", brand: "The Ordinary", productType: "serum", skinTypes: ["normal", "dry", "combination"], goals: ["brightening", "anti-aging"], avoidFor: ["vitamin-c-sensitive"], priceTier: "budget", productUrl: "https://amzn.to/4vu7jCM", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["vitamin-c-derivative", "oil-soluble"] },
  { id: "the-ordinary-euk-134", name: "EUK 134 0.1% Antioxidant Serum", brand: "The Ordinary", productType: "serum", skinTypes: ["normal", "combination", "mature"], goals: ["anti-aging"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4eHESKm", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["antioxidant", "euk-134"] },
  { id: "the-ordinary-marine-hyaluronics", name: "Marine Hyaluronics", brand: "The Ordinary", productType: "serum", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4b89L9E", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["hyaluronic-acid", "marine"] },
  { id: "cosrx-snail-peptide-eye-cream", name: "Advanced Snail Peptide Eye Cream", brand: "COSRX", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["snail-allergy"], priceTier: "budget", productUrl: "https://amzn.to/44eIWgt", ...e, affiliateSource: "amazon", imageUrl: "https://cdn.shopify.com/s/files/1/0513/3775/6828/files/advanced-snail-peptide-eye-cream-cosrx-official-1.png?v=1724835637", tags: ["snail-mucin", "peptides", "eye"] },
  { id: "charlotte-tilbury-magic-eye-rescue", name: "Magic Eye Rescue Moisturiser", brand: "Charlotte Tilbury", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4vuy9uz", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["eye", "retinol"] },
  { id: "skinceuticals-triple-lipid-restore", name: "Triple Lipid Restore 2:4:2", brand: "SkinCeuticals", productType: "barrier repair", skinTypes: ["dry", "normal", "mature"], goals: ["barrier repair", "anti-aging"], avoidFor: [], priceTier: "premium", productUrl: "https://amzn.to/3ShpsFd", ...e, affiliateSource: "amazon", imageUrl: "https://www.skinceuticals.sg/dw/image/v2/BFZM_PRD/on/demandware.static/-/Sites-skinceuticals-master-catalog/default/dw19b2a1ef/Products/3606000434967/TripleLipidRestore242_800x800px.jpg", tags: ["ceramides", "cholesterol", "fatty-acids"] },
  { id: "bioderma-atoderm-cream-ultra", name: "Atoderm Cream Ultra-Nourishing", brand: "Bioderma", productType: "barrier repair", skinTypes: ["very-dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4w93jr8", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["lipid-complex", "fragrance-free"] },
  { id: "purito-from-green-cleansing-oil", name: "From Green Cleansing Oil", brand: "Purito", productType: "cleanser", skinTypes: ["normal", "combination", "dry"], goals: ["makeup-removal", "gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4xOGB9e", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["oil-cleanser", "double-cleanse"] },
  { id: "bioderma-sensibio-foaming-gel", name: "Sensibio Foaming Gel", brand: "Bioderma", productType: "cleanser", skinTypes: ["sensitive", "normal", "combination"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "mid-range", productUrl: "https://amzn.to/4vNtPGZ", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["fragrance-free", "foaming"] },
  { id: "laneige-water-bank-cleansing-foam", name: "Water Bank Cleansing Foam Gentle Line", brand: "Laneige", productType: "cleanser", skinTypes: ["normal", "combination", "dry"], goals: ["gentle-cleanse", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://amzn.to/4adVZCe", ...e, affiliateSource: "amazon", imageUrl: "https://cdn.shopify.com/s/files/1/0255/0189/2660/files/WB_cleansingfoam_1x1_796f605a-be20-402c-be38-f9a1069c4ae7.jpg?v=1772748438", tags: ["foam", "hyaluronic-acid"] },
  { id: "sulwhasoo-gentle-cleansing-oil", name: "Gentle Cleansing Oil", brand: "Sulwhasoo", productType: "cleanser", skinTypes: ["dry", "normal", "combination"], goals: ["makeup-removal", "gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: "https://amzn.to/4oKdhfW", ...e, affiliateSource: "amazon", imageUrl: "https://cdn.shopify.com/s/files/1/0249/8399/4413/files/SWS_AZ_SE_Thumbnail_GCO_2000x2000_200ml.jpg?v=1688664789", tags: ["oil-cleanser", "hanbang"] },
  { id: "cosrx-propolis-synergy-toner", name: "Full Fit Propolis Synergy Toner", brand: "COSRX", productType: "toner", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "soothing"], avoidFor: ["propolis-allergy"], priceTier: "budget", productUrl: "https://amzn.to/4xTbJEW", ...e, affiliateSource: "amazon", imageUrl: "https://cdn.shopify.com/s/files/1/0513/3775/6828/files/full-fit-propolis-synergy-toner-cosrx-official-1.jpg?v=1724835425", tags: ["propolis", "honey"] },
  { id: "paulas-choice-smoothing-treatment-10-aha", name: "Advanced Smoothing Treatment 10% Glycolic AHA", brand: "Paula's Choice", productType: "toner", skinTypes: ["normal", "combination", "mature"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "mid-range", productUrl: "https://amzn.to/3Sp5uII", ...e, affiliateSource: "amazon", imageUrl: "", tags: ["glycolic-acid", "aha"] },
  { id: "paulas-choice-clear-anti-redness-bha", name: "Clear Anti-Redness Exfoliating Solution 2% BHA", brand: "Paula's Choice", productType: "toner", skinTypes: ["oily", "acne-prone", "sensitive"], goals: ["acne", "soothing"], avoidFor: ["pregnancy"], priceTier: "mid-range", productUrl: "https://amzn.to/4vxQmas", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2421253-main-zoom.jpg", tags: ["salicylic-acid", "anti-redness"] },
  { id: "the-ordinary-azelaic-acid-suspension", name: "Azelaic Acid Suspension 10%", brand: "The Ordinary", productType: "acne treatment", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["acne", "brightening"], avoidFor: [], priceTier: "budget", productUrl: "https://amzn.to/4oHSk5o", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2031458-main-zoom.jpg", tags: ["azelaic-acid", "suspension"] },
  { id: "the-ordinary-mandelic-acid-10", name: "Mandelic Acid 10% + HA", brand: "The Ordinary", productType: "acne treatment", skinTypes: ["oily", "acne-prone", "sensitive"], goals: ["acne", "texture"], avoidFor: ["pregnancy"], priceTier: "budget", productUrl: "https://amzn.to/4xQiWFG", ...e, affiliateSource: "amazon", imageUrl: "https://www.sephora.com/productimages/sku/s2210623-main-zoom.jpg", tags: ["mandelic-acid", "aha"] },

  // --- Stylevana affiliate (Linksynergy PDP) ---
  { id: "skin1004-madagascar-centella-ampoule-sv", name: "Madagascar Centella Ampoule", brand: "SKIN1004", productType: "serum", skinTypes: ["sensitive", "combination", "dry"], goals: ["soothing", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fskin1004-madagascar-centella-ampoule-100ml31725.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/s/k/skin1004-madagascar-centella-ampoule-100ml-368.jpg", tags: ["centella", "k-beauty"] },
  { id: "skin1004-hyalu-cica-water-fit-sun-serum-sv", name: "Madagascar Centella Hyalu-Cica Water-Fit Sun Serum SPF50 PA++++", brand: "SKIN1004", productType: "sunscreen", skinTypes: ["normal", "combination", "sensitive"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fskin1004-madagascar-centella-hyalu-cica-water-fit-sun-serum-spf50-pa-50ml60920.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/s/k/skin1004-madagascar-centella-hyalu-cica-water-fit-sun-serum-spf50-pa-50ml-185.jpg", tags: ["spf50", "centella", "hyaluronic-acid"] },
  { id: "medicube-zero-pore-pad-2-sv", name: "Zero Pore Pad 2.0", brand: "Medicube", productType: "toner", skinTypes: ["oily", "combination", "acne-prone"], goals: ["texture", "oil-control"], avoidFor: ["pregnancy"], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fmedicube-zero-pore-pad-2-0-70pcs44781.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/m/e/medicube-zero-pore-pad-2-0-70pcs-585.jpg", tags: ["exfoliating-pads", "toner-pads", "aha"] },
  { id: "mixsoon-bean-essence-sv", name: "Bean Essence", brand: "mixsoon", productType: "serum", skinTypes: ["combination", "oily", "normal"], goals: ["hydration", "texture"], avoidFor: [], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fmixsoon-bean-essence-50ml42996.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/m/i/mixsoon-bean-essence-50ml-171.jpg", tags: ["fermented-soybean", "essence-layer", "k-beauty"] },
  { id: "isntree-ha-watery-sun-gel-sv", name: "Hyaluronic Acid Watery Sun Gel SPF50+ PA++++", brand: "Isntree", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fisntree-hyaluronic-acid-watery-sun-gel-spf50-pa-50ml59795.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/i/s/isntree-hyaluronic-acid-watery-sun-gel-spf50-pa-50ml-851.jpg", tags: ["spf50", "hyaluronic-acid"] },
  { id: "haruharu-black-rice-toner-ff-sv", name: "Black Rice Hyaluronic Toner (Fragrance Free)", brand: "Haruharu WONDER", productType: "toner", skinTypes: ["sensitive", "dry", "normal"], goals: ["hydration", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fharuharu-wonder-black-rice-hyaluronic-toner-fragrance-free-150ml62015.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/h/a/haruharu-wonder-black-rice-hyaluronic-toner-fragrance-free-150ml-686.jpg", tags: ["black-rice", "fragrance-free"] },
  { id: "dr-althea-345-relief-cream-sv", name: "345 Relief Cream", brand: "Dr. Althea", productType: "barrier repair", skinTypes: ["sensitive", "combination", "normal"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fdr-althea-345-relief-cream-50ml36724.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/d/r/dr-althea-345-relief-cream-50ml-585.jpg", tags: ["barrier-support", "k-beauty"] },
  { id: "etude-soon-jung-2x-barrier-cream-sv", name: "Soon Jung 2x Barrier Intensive Cream", brand: "ETUDE", productType: "barrier repair", skinTypes: ["sensitive", "dry", "normal"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fetude-soon-jung-2x-barrier-intensive-cream-2023-new-version-60ml37153.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/e/t/etude-house-soon-jung-2x-barrier-intensive-cream-2023-new-version-60ml-580.jpg", tags: ["panthenol-line", "sensitive-skin"] },
  { id: "boj-dynasty-cream-sv", name: "Dynasty Cream", brand: "Beauty of Joseon", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "radiance"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fbeauty-of-joseon-dynasty-cream-50ml36385.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/b/e/beauty-of-joseon-dynasty-cream-50ml-178.jpg", tags: ["hanbang", "cream"] },
  { id: "cosrx-bha-blackhead-power-sv", name: "BHA Blackhead Power Liquid", brand: "COSRX", productType: "acne treatment", skinTypes: ["oily", "combination", "acne-prone"], goals: ["texture", "oil-control"], avoidFor: ["pregnancy"], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fcosrx-bha-blackhead-power-liquid-100ml42411.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/c/o/cosrx-bha-blackhead-power-liquid-100ml-293.jpg", tags: ["bha", "leave-on-exfoliant"] },
  { id: "cosrx-snail-92-cream-sv", name: "Advanced Snail 92 All In One Cream", brand: "COSRX", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "barrier repair"], avoidFor: ["snail-allergy"], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fcosrx-advanced-snail-92-all-in-one-cream-100g36621.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/c/o/cosrx-advanced-snail-92-all-in-one-cream-93.jpg", tags: ["snail-mucin", "gel-cream"] },
  { id: "laneige-lip-sleeping-mask-ex-sv", name: "Lip Sleeping Mask EX", brand: "LANEIGE", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Flaneige-lip-sleeping-mask-ex-3g.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/l/a/laneige-lip-sleeping-mask-ex-3g-82.jpg", tags: ["lip-care", "overnight"] },
  { id: "illiyoon-ceramide-ato-cream-sv", name: "Ceramide Ato Concentrate Cream", brand: "ILLIYOON", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Filliyoon-ceramide-ato-concentrate-cream-230ml107452.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/i/l/illiyoon-ceramide-ato-concentrate-cream-230ml-956.jpg", tags: ["ceramide", "fragrance-free"] },
  { id: "dear-klairs-supple-unscented-toner-sv", name: "Supple Preparation Unscented Toner", brand: "Dear, Klairs", productType: "toner", skinTypes: ["sensitive", "dry", "normal"], goals: ["hydration", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fdear-klairs-supple-preparation-unscented-toner.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/d/e/dear-klairs-supple-preparation-unscented-toner-704.jpg", tags: ["fragrance-free", "layering-toner"] },
  { id: "axis-y-dark-spot-glow-serum-sv", name: "Dark Spot Correcting Glow Serum", brand: "AXIS-Y", productType: "serum", skinTypes: ["combination", "oily", "normal"], goals: ["brightening", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Faxis-y-dark-spot-correcting-glow-serum-50ml55927.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/a/x/axis-y-dark-spot-correcting-glow-serum-50ml-257.jpg", tags: ["niacinamide", "dark-spots"] },
  { id: "anua-peach-70-niacin-set-sv", name: "Peach 70 Niacin Serum (2ea Set)", brand: "Anua", productType: "serum", skinTypes: ["normal", "combination"], goals: ["brightening", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fanua-peach-70-niacin-serum-30ml-2ea-set.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/a/n/anua-peach-70-niacin-serum-30ml-2ea-set-293.jpg", tags: ["niacinamide", "peach-extract"] },
  { id: "boj-matte-sun-stick-sv", name: "Matte Sun Stick : Mugwort + Camelia SPF50+ PA++++", brand: "Beauty of Joseon", productType: "sunscreen", skinTypes: ["oily", "combination", "normal"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fbeauty-of-joseon-matte-sun-stick-mugwort-camelia-spf50-pa-18g54373.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/b/e/beauty-of-joseon-matte-sun-stick-mugwort-camelia-spf50-pa-18g-637.jpg", tags: ["spf50", "sun-stick"] },
  { id: "etude-soon-jung-ph55-toner-sv", name: "Soon Jung PH 5.5 Relief Toner", brand: "ETUDE", productType: "toner", skinTypes: ["sensitive", "dry", "normal"], goals: ["soothing", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fetude-soon-jung-ph-5-5-relief-toner.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/e/t/etude-house-soon-jung-ph-5-5-relief-toner-123.jpg", tags: ["sensitive-line", "weakly-acidic"] },
  { id: "manyo-pure-cleansing-oil-sv", name: "Pure Cleansing Oil", brand: "Ma:nyo", productType: "cleanser", skinTypes: ["normal", "combination", "dry"], goals: ["makeup-removal", "gentle-cleanse"], avoidFor: [], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fma-nyo-pure-cleansing-oil-200ml35631.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/m/a/ma-nyo-pure-cleansing-oil-200ml-38.jpg", tags: ["cleansing-oil", "double-cleanse"] },
  { id: "cosrx-salicylic-daily-gentle-sv", name: "Salicylic Acid Daily Gentle Cleanser", brand: "COSRX", productType: "cleanser", skinTypes: ["oily", "combination", "acne-prone"], goals: ["gentle-cleanse", "oil-control"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fcosrx-salicylic-acid-daily-gentle-cleanser-150ml32810.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/c/o/cosrx-salicylic-acid-daily-gentle-cleanser-177.jpg", tags: ["salicylic-acid", "bha-cleanser"] },
  { id: "some-by-mi-yuja-niacin-serum-sv", name: "Yuja Niacin Anti Blemish Serum", brand: "SOME BY MI", productType: "serum", skinTypes: ["normal", "combination"], goals: ["brightening", "texture"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fsome-by-mi-yuja-niacin-anti-blemish-serum-50ml57692.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/s/o/some-by-mi-some-by-mi-yuja-niacin-anti-blemish-serum-50ml-959.jpg", tags: ["vitamin-c", "niacinamide"] },
  { id: "benton-snail-bee-essence-new-sv", name: "Snail Bee High Content Essence (New Version)", brand: "Benton", productType: "serum", skinTypes: ["sensitive", "dry", "normal"], goals: ["soothing", "hydration"], avoidFor: ["snail-allergy"], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fbenton-snail-bee-high-content-essence-new-version-100ml42317.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/b/e/benton-snail-bee-high-content-essence-new-version-100ml-889.jpg", tags: ["snail-mucin", "classic-k-beauty"] },
  { id: "isntree-green-tea-fresh-toner-sv", name: "Green Tea Fresh Toner", brand: "Isntree", productType: "toner", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fisntree-green-tea-fresh-toner.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/i/s/isntree-green-tea-fresh-toner--526.jpg", tags: ["green-tea", "refreshing-toner"] },
  { id: "abib-heartleaf-spot-pad-sv", name: "Heartleaf Spot Pad Calming Touch", brand: "Abib", productType: "toner", skinTypes: ["sensitive", "combination", "oily"], goals: ["soothing", "oil-control"], avoidFor: [], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fabib-heartleaf-spot-pad-calming-touch-150ml-80pads44341.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/a/b/abib-heartleaf-spot-pad-calming-touch-150ml-80pads-93.jpg", tags: ["heartleaf", "toner-pads"] },
  { id: "boj-ginseng-essence-water-sv", name: "Ginseng Essence Water", brand: "Beauty of Joseon", productType: "toner", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "radiance"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fbeauty-of-joseon-ginseng-essence-water-150ml-5-fl-oz42365.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/b/e/beauty-of-joseon-ginseng-essence-water-150ml-5-fl-oz--101.jpg", tags: ["ginseng", "essence-toner"] },
  { id: "skin1004-tea-trica-ampoule-sv", name: "Madagascar Centella Tea-Trica Relief Ampoule", brand: "SKIN1004", productType: "serum", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["soothing", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fskin1004-madagascar-centella-tea-trica-relief-ampoule-100ml31719.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/s/k/skin1004-madagascar-centella-tea-trica-relief-ampoule-100ml-832.jpg", tags: ["centella", "tea-tree-note"] },
  { id: "haruharu-black-rice-ha-essence-sv", name: "Black Rice Hyaluronic Essence", brand: "Haruharu WONDER", productType: "serum", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "radiance"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fharuharu-wonder-black-rice-hyaluronic-essence-50ml42604.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/h/a/haruharu-wonder-black-rice-hyaluronic-essence-50ml-513.jpg", tags: ["black-rice", "hyaluronic-acid"] },
  { id: "medicube-deep-vita-c-ampoule-sv", name: "Deep Vita C Ampoule 2.0", brand: "Medicube", productType: "serum", skinTypes: ["normal", "combination"], goals: ["brightening", "antioxidant"], avoidFor: ["vitamin-c-sensitive"], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fmedicube-deep-vita-c-ampoule-2-0-10g-3ea31282.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/m/e/medicube-deep-vita-c-ampoule-2-0-10g-3ea-516.jpg", tags: ["vitamin-c", "ampoule"] },
  // MANUAL REVIEW: display name says cleansing water; Stylevana murl slug is cleansing-foam — confirm PDP vs inventory before relying on SKU.
  { id: "torriden-dive-in-cleansing-water-sv", name: "DIVE-IN Low Molecular Hyaluronic Acid Cleansing Water", brand: "Torriden", productType: "cleanser", skinTypes: ["normal", "sensitive", "dry"], goals: ["gentle-cleanse", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Ftorriden-dive-in-low-molecular-hyaluronic-acid-cleansing-foam-150ml34648.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/t/o/torriden-dive-in-low-molecular-hyaluronic-acid-cleansing-foam-150ml-779.jpg", tags: ["torriden", "first-cleanse"] },
  { id: "im-from-rice-toner-sv", name: "Rice Toner", brand: "I'm From", productType: "toner", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "radiance"], avoidFor: [], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fi-m-from-rice-toner-150ml62098.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/i/-/i-m-from-rice-toner-150ml-899.jpg", tags: ["rice", "brightening-toner"] },
  { id: "numbuzin-no3-softening-serum-sv", name: "No. 3 Skin Softening Serum", brand: "numbuzin", productType: "serum", skinTypes: ["normal", "combination", "dry"], goals: ["texture", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fnumbuz-n-no-3-skin-softening-serum-50ml.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/n/u/numbuz-n-no-3-skin-softening-serum-50ml-49.jpg", tags: ["ferment-glow", "texture"] },
  { id: "cosrx-poreless-power-liquid-sv", name: "Two In One Poreless Power Liquid", brand: "COSRX", productType: "acne treatment", skinTypes: ["oily", "combination"], goals: ["oil-control", "texture"], avoidFor: ["pregnancy"], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fcosrx-two-in-one-poreless-power-liquid.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/c/o/cosrx-two-in-one-poreless-power-liquid-143.jpg", tags: ["bha", "pores"] },
  { id: "purito-wonder-releaf-centella-unscented-sv", name: "Centella Unscented Serum", brand: "Purito", productType: "serum", skinTypes: ["sensitive", "dry", "normal"], goals: ["soothing", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fpurito-seoul-wonder-releaf-centella-serum-unscented-60ml57417.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/p/u/purito-seoul-wonder-releaf-centella-serum-unscented-60ml-897.jpg", tags: ["centella", "fragrance-free"] },
  { id: "round-lab-dokdo-cleansing-oil-sv", name: "1025 Dokdo Cleansing Oil", brand: "Round Lab", productType: "cleanser", skinTypes: ["normal", "combination", "dry"], goals: ["makeup-removal", "gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fround-lab-1025-dokdo-cleansing-oil-200ml35670.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/r/o/round-lab-1025-dokdo-cleansing-oil-200ml-629.jpg", tags: ["dokdo-line", "cleansing-oil"] },
  { id: "skin1004-tone-brightening-capsule-sv", name: "Madagascar Centella Tone Brightening Capsule Ampoule", brand: "SKIN1004", productType: "serum", skinTypes: ["combination", "normal"], goals: ["brightening", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fskin1004-madagascar-centella-tone-brightening-capsule-ampoule-100ml31723.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/s/k/skin1004-madagascar-centella-tone-brightening-capsule-ampoule-100ml-708.jpg", tags: ["centella", "brightening"] },
  { id: "cosrx-hydrium-ha-ampoule-sv", name: "Hydrium Triple Hyaluronic Moisture Ampoule", brand: "COSRX", productType: "serum", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fcosrx-hydrium-triple-hyaluronic-moisture-ampoule-40ml30853.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/c/o/cosrx-hydrium-triple-hyaluronic-moisture-ampoule-40ml-474.jpg", tags: ["hyaluronic-acid", "hydrium"] },
  { id: "dr-g-green-mild-up-sun-sv", name: "Green Mild Up Sun+ SPF50+ PA++++", brand: "Dr.G", productType: "sunscreen", skinTypes: ["sensitive", "normal", "dry"], goals: ["sun protection", "soothing"], avoidFor: [], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fdr-g-green-mild-up-sun-spf50-pa-50ml59401.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/d/r/dr-g-green-mild-up-sun-spf50-pa-50ml-167.jpg", tags: ["spf50", "sensitive-route"] },
  { id: "boj-apricot-peeling-gel-sv", name: "Apricot Blossom Peeling Gel", brand: "Beauty of Joseon", productType: "cleanser", skinTypes: ["normal", "combination"], goals: ["texture", "gentle-cleanse"], avoidFor: ["sensitive"], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fbeauty-of-joseon-apricot-blossom-peeling-gel-100ml55001.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/b/e/beauty-of-joseon-apricot-blossom-peeling-gel-100ml-358.jpg", tags: ["peeling-gel", "exfoliating"] },
  { id: "torriden-balanceful-cica-serum-sv", name: "Balanceful Cica Serum", brand: "Torriden", productType: "serum", skinTypes: ["sensitive", "combination", "oily"], goals: ["soothing", "hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Ftorriden-balanceful-cica-serum-50ml57770.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/t/o/torriden-balanceful-cica-serum-50ml-938.jpg", tags: ["cica", "balancing"] },
  { id: "skin1004-probio-cica-intensive-sv", name: "Madagascar Centella Probio-Cica Intensive Ampoule", brand: "SKIN1004", productType: "serum", skinTypes: ["sensitive", "dry", "normal"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fskin1004-madagascar-centella-probio-cica-intensive-ampoule-30ml31710.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/s/k/skin1004-madagascar-centella-probio-cica-intensive-ampoule-30ml-64.jpg", tags: ["centella", "barrier-support"] },
  { id: "wellage-real-hyaluronic-blue-ampoule-sv", name: "Real Hyaluronic Blue 100 Ampoule", brand: "Wellage", productType: "serum", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fwellage-real-hyaluronic-blue-ampoule-60ml105427.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/w/e/wellage-real-hyaluronic-blue-ampoule-60ml-779.jpg", tags: ["hyaluronic-acid", "ampoule"] },
  { id: "anua-azelaic-hyaluron-serum-sv", name: "Azelaic Acid 10 Hyaluron Redness Soothing Serum", brand: "Anua", productType: "serum", skinTypes: ["sensitive", "combination"], goals: ["soothing", "texture"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fanua-azelaic-acid-10-hyaluron-redness-soothing-serum-30ml95845.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/a/n/anua-azelaic-acid-10-hyaluron-redness-soothing-serum-30ml-701.jpg", tags: ["azelaic-acid", "redness"] },
  { id: "isntree-ultra-low-ha-toner-sv", name: "Ultra-Low Molecular Hyaluronic Acid Toner", brand: "Isntree", productType: "toner", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "budget", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fisntree-ultra-low-molecular-hyaluronic-acid-toner-300ml62207.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/i/s/isntree-ultra-low-molecular-hyaluronic-acid-toner-300ml-62.jpg", tags: ["hyaluronic-acid", "layering-toner"] },
  // MANUAL REVIEW: classic name "Bio-Peel Gauze Peeling Lemon" vs PDP slug "Lemon Bright PHA Gauze Peeling" — confirm same line/variant.
  { id: "neogen-lemon-bright-pha-peeling-sv", name: "Bio-Peel Gauze Peeling Lemon", brand: "NEOGEN Dermalogy", productType: "toner", skinTypes: ["normal", "combination", "oily"], goals: ["texture", "radiance"], avoidFor: ["pregnancy"], priceTier: "mid-range", productUrl: "https://click.linksynergy.com/deeplink?id=m0xFY0twc/8&mid=53421&murl=https%3A%2F%2Fwww.stylevana.com%2Fen_CA%2Fneogen-dermalogy-lemon-bright-pha-gauze-peeling-190ml-30ea55182.html", ...e, affiliateSource: "stylevana", imageUrl: "https://sv5-cdn.stylevana.com/media/catalog/product/cache/259eb194bcbc48ab4e79d79bf0926d73/n/e/neogen-dermalogy-lemon-bright-pha-gauze-peeling-190ml-30ea-309.jpg", tags: ["pha", "gauze-peel", "exfoliating-pads"] },

  // Amazon-only list: rows still missing here (e.g. many Cetaphil / Naturium / Bubble / Medik8 SKUs) — add or map in a later pass.
];

export const skincareProductCount = skincareProducts.length;
