/**
 * Curated skincare product records for /skincare-checker (not wired to UI yet).
 *
 * TODO: Later move this database to Firebase or CSV import when product count grows to 1000+.
 */

export type SkincareProductType =
  | "moisturizer"
  | "serum"
  | "sunscreen"
  | "cleanser"
  | "toner"
  | "acne treatment"
  | "barrier repair";

export type SkincarePriceTier = "budget" | "mid-range" | "premium";

export type SkincareProduct = {
  id: string;
  name: string;
  brand: string;
  productType: SkincareProductType;
  skinTypes: string[];
  goals: string[];
  avoidFor: string[];
  priceTier: SkincarePriceTier;
  imageUrl: string;
  productUrl: string;
  affiliateSource: string;
  tags: string[];
};

const e = {
  imageUrl: "",
  productUrl: "",
  affiliateSource: "",
} as const;

export const skincareProducts: SkincareProduct[] = [
  // --- 25 moisturizers ---
  { id: "cerave-moisturizing-cream", name: "Moisturizing Cream", brand: "CeraVe", productType: "moisturizer", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", ...e, tags: ["ceramides", "fragrance-free", "mve"] },
  { id: "cerave-daily-moisturizing-lotion", name: "Daily Moisturizing Lotion", brand: "CeraVe", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", ...e, tags: ["ceramides", "lightweight", "fragrance-free"] },
  { id: "vanicream-moisturizing-cream", name: "Moisturizing Cream", brand: "Vanicream", productType: "moisturizer", skinTypes: ["sensitive", "dry"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", ...e, tags: ["minimal-ingredients", "eczema-friendly"] },
  { id: "neutrogena-hydro-boost-water-gel", name: "Hydro Boost Water Gel", brand: "Neutrogena", productType: "moisturizer", skinTypes: ["oily", "combination", "normal"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["hyaluronic-acid", "gel"] },
  { id: "larocheposay-toleriane-double-repair", name: "Toleriane Double Repair Face Moisturizer", brand: "La Roche-Posay", productType: "moisturizer", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["ceramides", "niacinamide", "fragrance-free"] },
  { id: "first-aid-beauty-ultra-repair-cream", name: "Ultra Repair Cream", brand: "First Aid Beauty", productType: "moisturizer", skinTypes: ["dry", "sensitive"], goals: ["barrier repair", "soothing"], avoidFor: ["eucalyptus-sensitive"], priceTier: "mid-range", ...e, tags: ["colloidal-oatmeal", "rich"] },
  { id: "kiehls-ultra-facial-cream", name: "Ultra Facial Cream with Squalane", brand: "Kiehl's", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["squalane", "glacial-glycoprotein"] },
  { id: "weleda-skin-food-original", name: "Skin Food Original Ultra-Rich Cream", brand: "Weleda", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["barrier repair"], avoidFor: ["essential-oil-sensitive", "fragrance-sensitive"], priceTier: "budget", ...e, tags: ["botanicals", "rich"] },
  { id: "eucerin-advanced-repair-cream", name: "Advanced Repair Cream", brand: "Eucerin", productType: "moisturizer", skinTypes: ["dry", "very-dry"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", ...e, tags: ["urea", "ceramide"] },
  { id: "aveeno-calm-restore-oat-gel", name: "Calm + Restore Oat Gel Moisturizer", brand: "Aveeno", productType: "moisturizer", skinTypes: ["sensitive", "dry"], goals: ["soothing", "barrier repair"], avoidFor: [], priceTier: "budget", ...e, tags: ["oat", "fragrance-free"] },
  { id: "peter-thomas-roth-water-drench", name: "Water Drench Hyaluronic Cloud Cream", brand: "Peter Thomas Roth", productType: "moisturizer", skinTypes: ["combination", "oily", "normal"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["hyaluronic-acid", "gel-cream"] },
  { id: "drunk-elephant-protini", name: "Protini Polypeptide Cream", brand: "Drunk Elephant", productType: "moisturizer", skinTypes: ["normal", "combination", "dry"], goals: ["anti-aging", "hydration"], avoidFor: [], priceTier: "premium", ...e, tags: ["peptides", "amino-acids"] },
  { id: "tatcha-the-water-cream", name: "The Water Cream", brand: "Tatcha", productType: "moisturizer", skinTypes: ["oily", "combination", "normal"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["japanese-leopard-lily", "oil-free"] },
  { id: "clinique-ddmg", name: "Dramatically Different Moisturizing Gel", brand: "Clinique", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["oil-free", "gel"] },
  { id: "origins-ginzing-gel", name: "GinZing Energy-Boosting Gel Moisturizer", brand: "Origins", productType: "moisturizer", skinTypes: ["normal", "combination"], goals: ["hydration", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["caffeine", "ginseng"] },
  { id: "embryolisse-lait-creme-concentre", name: "Lait-Crème Concentré", brand: "Embryolisse", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["multi-use", "makeup-primer"] },
  { id: "nivea-creme", name: "Creme", brand: "Nivea", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["barrier repair"], avoidFor: ["fragrance-sensitive", "fungal-acne-prone"], priceTier: "budget", ...e, tags: ["petrolatum-rich", "classic"] },
  { id: "stratia-liquid-gold", name: "Liquid Gold", brand: "Stratia", productType: "moisturizer", skinTypes: ["dry", "sensitive", "barrier-damaged"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["ceramides", "cholesterol", "fatty-acids"] },
  { id: "paulas-choice-omega-complex-moisturizer", name: "Omega+ Complex Moisturizer", brand: "Paula's Choice", productType: "moisturizer", skinTypes: ["dry", "normal", "sensitive"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["omega-oils", "ceramides"] },
  { id: "belif-aqua-bomb", name: "The True Cream Aqua Bomb", brand: "belif", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["gel-cream", "cooling"] },
  { id: "it-cosmetics-confidence-cream", name: "Confidence in a Cream Hydrating Moisturizer", brand: "IT Cosmetics", productType: "moisturizer", skinTypes: ["dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["collagen", "peptides"] },
  { id: "yttp-superfood-air-whip", name: "Superfood Air-Whip Moisture Cream", brand: "Youth To The People", productType: "moisturizer", skinTypes: ["combination", "normal"], goals: ["hydration"], avoidFor: ["essential-oil-sensitive"], priceTier: "mid-range", ...e, tags: ["kale", "spinach", "hyaluronic-acid"] },
  { id: "glow-recipe-plum-plump-cream", name: "Plum Plump Hyaluronic Cream", brand: "Glow Recipe", productType: "moisturizer", skinTypes: ["normal", "combination", "dry"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["plum", "hyaluronic-acid"] },
  { id: "summer-fridays-cloud-dew", name: "Cloud Dew Oil-Free Gel Cream Moisturizer", brand: "Summer Fridays", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["oil-free", "amino-acids"] },
  { id: "olay-regenerist-micro-sculpting-cream", name: "Regenerist Micro-Sculpting Cream", brand: "Olay", productType: "moisturizer", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["niacinamide", "peptides"] },

  // --- 20 sunscreens ---
  { id: "eltamd-uv-clear-spf46", name: "UV Clear Broad-Spectrum SPF 46", brand: "EltaMD", productType: "sunscreen", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["oil-control", "sun protection"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["mineral-leaning", "niacinamide", "dermatologist-favorite"] },
  { id: "larocheposay-anthelios-melt-in-milk-spf60", name: "Anthelios Melt-in Milk Sunscreen SPF 60", brand: "La Roche-Posay", productType: "sunscreen", skinTypes: ["normal", "dry", "sensitive"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["broad-spectrum", "water-resistant"] },
  { id: "supergoop-unseen-sunscreen-spf40", name: "Unseen Sunscreen SPF 40", brand: "Supergoop", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: ["silicone-sensitive"], priceTier: "mid-range", ...e, tags: ["chemical", "primer-feel"] },
  { id: "cerave-hydrating-mineral-spf30", name: "Hydrating Mineral Sunscreen SPF 30", brand: "CeraVe", productType: "sunscreen", skinTypes: ["sensitive", "dry", "normal"], goals: ["sun protection", "barrier repair"], avoidFor: [], priceTier: "budget", ...e, tags: ["mineral", "ceramides"] },
  { id: "neutrogena-ultra-sheer-spf55", name: "Ultra Sheer Dry-Touch Sunscreen SPF 55", brand: "Neutrogena", productType: "sunscreen", skinTypes: ["normal", "oily", "combination"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["chemical", "dry-touch"] },
  { id: "australian-gold-botanical-tinted-spf50", name: "Botanical Tinted Face Sunscreen SPF 50", brand: "Australian Gold", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", ...e, tags: ["mineral", "tinted"] },
  { id: "isdin-eryfotona-actinica-spf50", name: "Eryfotona Actinica Mineral Sunscreen SPF 50+", brand: "ISDIN", productType: "sunscreen", skinTypes: ["normal", "dry", "mature"], goals: ["sun protection", "anti-aging"], avoidFor: [], priceTier: "premium", ...e, tags: ["mineral", "dna-repairosomes"] },
  { id: "blue-lizard-sensitive-mineral-spf50", name: "Sensitive Mineral Sunscreen SPF 50+", brand: "Blue Lizard", productType: "sunscreen", skinTypes: ["sensitive", "children"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["mineral", "reef-conscious-line"] },
  { id: "cosrx-aloe-soothing-sun-cream-spf50", name: "Aloe Soothing Sun Cream SPF 50 PA+++", brand: "COSRX", productType: "sunscreen", skinTypes: ["dry", "sensitive", "normal"], goals: ["sun protection", "soothing"], avoidFor: [], priceTier: "budget", ...e, tags: ["chemical", "aloe"] },
  { id: "beauty-of-joseon-relief-sun-spf50", name: "Relief Sun Rice + Probiotics SPF 50+ PA++++", brand: "Beauty of Joseon", productType: "sunscreen", skinTypes: ["normal", "dry", "sensitive"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", ...e, tags: ["chemical", "rice"] },
  { id: "skin-aqua-tone-up-uv-essence", name: "Tone Up UV Essence SPF 50+ PA++++", brand: "Skin Aqua", productType: "sunscreen", skinTypes: ["normal", "combination"], goals: ["sun protection", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["japanese", "tone-up"] },
  { id: "canmake-mermaid-skin-gel-uv", name: "Mermaid Skin Gel UV SPF 50+ PA++++", brand: "Canmake", productType: "sunscreen", skinTypes: ["normal", "oily", "combination"], goals: ["sun protection"], avoidFor: ["alcohol-sensitive"], priceTier: "budget", ...e, tags: ["gel", "japanese"] },
  { id: "black-girl-sunscreen-spf30", name: "Make Me Invisible SPF 30", brand: "Black Girl Sunscreen", productType: "sunscreen", skinTypes: ["all", "deeper-skin-tones"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", ...e, tags: ["no-white-cast-focus", "broad-spectrum"] },
  { id: "shiseido-ultimate-sun-protector-spf50", name: "Ultimate Sun Protector Cream SPF 50+ WetForce", brand: "Shiseido", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["wetforce", "synchroshield"] },
  { id: "drunk-elephant-umbra-sheer-spf30", name: "Umbra Sheer Physical Daily Defense SPF 30", brand: "Drunk Elephant", productType: "sunscreen", skinTypes: ["sensitive", "normal"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["mineral", "marula"] },
  { id: "biossance-squalane-zinc-spf30", name: "Squalane + Zinc Sheer Mineral Sunscreen SPF 30 PA +++", brand: "Biossance", productType: "sunscreen", skinTypes: ["sensitive", "dry", "normal"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["mineral", "squalane"] },
  { id: "sun-bum-original-spf50", name: "Original SPF 50 Sunscreen Lotion", brand: "Sun Bum", productType: "sunscreen", skinTypes: ["normal", "body"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["coconut-scent", "broad-spectrum"] },
  { id: "aveeno-protect-hydrate-spf60", name: "Protect + Hydrate Sunscreen Broad Spectrum SPF 60", brand: "Aveeno", productType: "sunscreen", skinTypes: ["dry", "normal"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "budget", ...e, tags: ["oat", "chemical"] },
  { id: "paulas-choice-youth-extending-fluid-spf50", name: "Youth-Extending Daily Hydrating Fluid SPF 50", brand: "Paula's Choice", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection", "anti-aging"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["antioxidants", "fluid"] },
  { id: "tower28-sunnydays-spf30", name: "SunnyDays SPF 30 Tinted Sunscreen Foundation", brand: "Tower 28", productType: "sunscreen", skinTypes: ["sensitive", "normal", "combination"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["tinted", "national-eczema-association-seal"] },

  // --- 20 serums ---
  { id: "the-ordinary-niacinamide-zinc", name: "Niacinamide 10% + Zinc 1%", brand: "The Ordinary", productType: "serum", skinTypes: ["oily", "acne-prone", "combination"], goals: ["oil-control", "pore appearance"], avoidFor: [], priceTier: "budget", ...e, tags: ["niacinamide", "zinc"] },
  { id: "skinceuticals-ce-ferulic", name: "C E Ferulic", brand: "SkinCeuticals", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "brightening"], avoidFor: ["vitamin-c-sensitive"], priceTier: "premium", ...e, tags: ["vitamin-c", "vitamin-e", "ferulic-acid"] },
  { id: "drunk-elephant-tlc-framboos", name: "T.L.C. Framboos Glycolic Resurfacing Night Serum", brand: "Drunk Elephant", productType: "serum", skinTypes: ["normal", "combination", "oily"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "premium", ...e, tags: ["aha", "bha", "blend"] },
  { id: "esteelauder-advanced-night-repair", name: "Advanced Night Repair Synchronized Multi-Recovery Complex", brand: "Estée Lauder", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["hyaluronic-acid", "bifida"] },
  { id: "lancome-genifique", name: "Advanced Génifique Youth Activating Serum", brand: "Lancôme", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["prebiotic", "hyaluronic-acid"] },
  { id: "olay-regenerist-micro-sculpting-serum", name: "Regenerist Micro-Sculpting Serum", brand: "Olay", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["niacinamide", "peptides"] },
  { id: "the-ordinary-ha-b5", name: "Hyaluronic Acid 2% + B5", brand: "The Ordinary", productType: "serum", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "budget", ...e, tags: ["hyaluronic-acid", "panthenol"] },
  { id: "paulas-choice-azelaic-acid-booster", name: "10% Azelaic Acid Booster", brand: "Paula's Choice", productType: "serum", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["brightening", "texture"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["azelaic-acid", "salicylic-acid"] },
  { id: "good-molecules-niacinamide-serum", name: "Niacinamide Serum", brand: "Good Molecules", productType: "serum", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "brightening"], avoidFor: [], priceTier: "budget", ...e, tags: ["niacinamide"] },
  { id: "vichy-mineral-89", name: "Minéral 89 Hyaluronic Acid Face Serum", brand: "Vichy", productType: "serum", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", ...e, tags: ["volcanic-water", "hyaluronic-acid"] },
  { id: "kiehls-midnight-recovery", name: "Midnight Recovery Concentrate Face Oil", brand: "Kiehl's", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["essential-oil-sensitive"], priceTier: "mid-range", ...e, tags: ["evening-primrose", "lavender-oil"] },
  { id: "biossance-vitamin-c-dark-spot", name: "Squalane + Vitamin C Dark Spot Serum", brand: "Biossance", productType: "serum", skinTypes: ["normal", "combination", "dry"], goals: ["brightening", "anti-aging"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["vitamin-c-derivative", "squalane"] },
  { id: "sunday-riley-good-genes", name: "Good Genes All-In-One Lactic Acid Treatment", brand: "Sunday Riley", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "premium", ...e, tags: ["lactic-acid"] },
  { id: "larocheposay-pure-vitamin-c10", name: "Pure Vitamin C10 Serum", brand: "La Roche-Posay", productType: "serum", skinTypes: ["normal", "combination"], goals: ["brightening"], avoidFor: ["vitamin-c-sensitive"], priceTier: "mid-range", ...e, tags: ["vitamin-c", "salicylic-acid"] },
  { id: "versed-press-restart-retinol", name: "Press Restart Gentle Retinol Serum", brand: "Versed", productType: "serum", skinTypes: ["normal", "combination", "mature"], goals: ["anti-aging", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", ...e, tags: ["retinol", "bakuchiol"] },
  { id: "glow-recipe-watermelon-dew-drops", name: "Watermelon Glow Niacinamide Dew Drops", brand: "Glow Recipe", productType: "serum", skinTypes: ["normal", "dry", "combination"], goals: ["brightening", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["niacinamide", "highlight"] },
  { id: "innisfree-green-tea-seed-serum", name: "Green Tea Seed Hyaluronic Serum", brand: "innisfree", productType: "serum", skinTypes: ["normal", "combination", "dry"], goals: ["hydration", "antioxidant"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["green-tea", "hyaluronic-acid"] },
  { id: "sulwhasoo-first-care-activating-serum", name: "First Care Activating Serum VI", brand: "Sulwhasoo", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["hanbang", "jaum"] },
  { id: "lancome-genifique-light-pearl", name: "Advanced Génifique Yeux Light-Pearl Eye & Lash Serum", brand: "Lancôme", productType: "serum", skinTypes: ["normal", "mature"], goals: ["anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["eye", "lash"] },
  { id: "the-ordinary-buffet-copper", name: "Buffet + Copper Peptides 1%", brand: "The Ordinary", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging"], avoidFor: ["vitamin-c-stacking"], priceTier: "budget", ...e, tags: ["peptides", "copper"] },

  // --- 15 cleansers ---
  { id: "cerave-hydrating-cleanser", name: "Hydrating Facial Cleanser", brand: "CeraVe", productType: "cleanser", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "gentle-cleanse"], avoidFor: [], priceTier: "budget", ...e, tags: ["ceramides", "non-foaming"] },
  { id: "cerave-foaming-cleanser", name: "Foaming Facial Cleanser", brand: "CeraVe", productType: "cleanser", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "gentle-cleanse"], avoidFor: [], priceTier: "budget", ...e, tags: ["niacinamide", "ceramides"] },
  { id: "larocheposay-toleriane-gentle-cleanser", name: "Toleriane Hydrating Gentle Cleanser", brand: "La Roche-Posay", productType: "cleanser", skinTypes: ["dry", "sensitive"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", ...e, tags: ["cream", "fragrance-free"] },
  { id: "vanicream-gentle-facial-cleanser", name: "Gentle Facial Cleanser", brand: "Vanicream", productType: "cleanser", skinTypes: ["sensitive", "dry"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", ...e, tags: ["minimal", "gluten-free"] },
  { id: "fresh-soy-face-cleanser", name: "Soy Face Cleanser", brand: "Fresh", productType: "cleanser", skinTypes: ["normal", "dry", "sensitive"], goals: ["gentle-cleanse", "hydration"], avoidFor: ["soy-allergy"], priceTier: "mid-range", ...e, tags: ["soy", "amino-acids"] },
  { id: "yttp-superfood-cleanser", name: "Superfood Antioxidant Cleanser", brand: "Youth To The People", productType: "cleanser", skinTypes: ["normal", "combination", "oily"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["kale", "spinach", "gel"] },
  { id: "neutrogena-fresh-foaming-cleanser", name: "Fresh Foaming Cleanser", brand: "Neutrogena", productType: "cleanser", skinTypes: ["normal", "combination"], goals: ["makeup-removal"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["foaming"] },
  { id: "cosrx-low-ph-good-morning", name: "Low pH Good Morning Gel Cleanser", brand: "COSRX", productType: "cleanser", skinTypes: ["oily", "combination", "acne-prone"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", ...e, tags: ["low-ph", "bha"] },
  { id: "krave-matcha-hemp-cleanser", name: "Matcha Hemp Hydrating Cleanser", brand: "Krave Beauty", productType: "cleanser", skinTypes: ["normal", "dry", "combination"], goals: ["hydration", "gentle-cleanse"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["matcha", "hemp"] },
  { id: "paulas-choice-resist-hydrating-cleanser", name: "RESIST Optimal Results Hydrating Cleanser", brand: "Paula's Choice", productType: "cleanser", skinTypes: ["dry", "normal", "sensitive"], goals: ["gentle-cleanse", "anti-aging"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["cream", "antioxidants"] },
  { id: "kiehls-ultra-facial-cleanser", name: "Ultra Facial Cleanser", brand: "Kiehl's", productType: "cleanser", skinTypes: ["normal", "combination", "dry"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["squalane", "apricot-kernel"] },
  { id: "glossier-milky-jelly-cleanser", name: "Milky Jelly Cleanser", brand: "Glossier", productType: "cleanser", skinTypes: ["normal", "dry", "sensitive"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["allantoin", "pro-vitamin-b5"] },
  { id: "innisfree-green-tea-foam-cleanser", name: "Green Tea Hyaluronic Acid Hydrating Foam Cleanser", brand: "innisfree", productType: "cleanser", skinTypes: ["normal", "combination", "oily"], goals: ["hydration", "gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", ...e, tags: ["green-tea", "foam"] },
  { id: "dhc-deep-cleansing-oil", name: "Deep Cleansing Oil", brand: "DHC", productType: "cleanser", skinTypes: ["dry", "normal", "combination"], goals: ["makeup-removal"], avoidFor: ["olive-oil-sensitive"], priceTier: "mid-range", ...e, tags: ["oil-cleanser", "double-cleanse"] },
  { id: "tatcha-rice-wash", name: "The Rice Wash Skin-Softening Cleanser", brand: "Tatcha", productType: "cleanser", skinTypes: ["normal", "dry", "combination"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["rice", "ph-neutral"] },

  // --- 10 toners / essences ---
  { id: "laneige-cream-skin-refiner", name: "Cream Skin Cerapeptide™ Toner & Moisturizer", brand: "Laneige", productType: "toner", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["ceramide", "milky-toner"] },
  { id: "cosrx-snail-96-essence", name: "Advanced Snail 96 Mucin Power Essence", brand: "COSRX", productType: "toner", skinTypes: ["dry", "normal", "sensitive"], goals: ["hydration", "barrier repair"], avoidFor: ["snail-allergy"], priceTier: "budget", ...e, tags: ["snail-mucin", "essence"] },
  { id: "missha-time-revolution-essence-5x", name: "Time Revolution The First Essence 5X", brand: "Missha", productType: "toner", skinTypes: ["normal", "dry", "mature"], goals: ["hydration", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["fermented", "first-essence"] },
  { id: "sk-ii-facial-treatment-essence", name: "Facial Treatment Essence", brand: "SK-II", productType: "toner", skinTypes: ["normal", "combination", "mature"], goals: ["texture", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", ...e, tags: ["pitera", "fermented"] },
  { id: "paulas-choice-2-bha-liquid", name: "Skin Perfecting 2% BHA Liquid Exfoliant", brand: "Paula's Choice", productType: "toner", skinTypes: ["oily", "acne-prone", "combination"], goals: ["texture", "pores"], avoidFor: ["pregnancy", "sensitive"], priceTier: "mid-range", ...e, tags: ["salicylic-acid", "leave-on"] },
  { id: "pyunkang-yul-essence-toner", name: "Essence Toner", brand: "Pyunkang Yul", productType: "toner", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "soothing"], avoidFor: [], priceTier: "budget", ...e, tags: ["minimal", "astringent-free"] },
  { id: "thayers-alcohol-free-toner", name: "Alcohol-Free Witch Hazel Facial Toner", brand: "Thayers", productType: "toner", skinTypes: ["normal", "combination", "oily"], goals: ["oil-control"], avoidFor: ["witch-hazel-sensitive"], priceTier: "budget", ...e, tags: ["witch-hazel", "aloe"] },
  { id: "dickinsons-enhanced-witch-hazel-toner", name: "Enhanced Witch Hazel Hydrating Toner", brand: "Dickinson's", productType: "toner", skinTypes: ["normal", "combination"], goals: ["hydration"], avoidFor: ["witch-hazel-sensitive"], priceTier: "budget", ...e, tags: ["witch-hazel", "hyaluronic-acid"] },
  { id: "hada-labo-gokujyun-lotion-moist", name: "Gokujyun Hyaluronic Acid Lotion (Moist)", brand: "Hada Labo", productType: "toner", skinTypes: ["dry", "normal"], goals: ["hydration"], avoidFor: [], priceTier: "budget", ...e, tags: ["hyaluronic-acid", "japanese"] },
  { id: "mario-badescu-glycolic-acid-toner", name: "Glycolic Acid Toner", brand: "Mario Badescu", productType: "toner", skinTypes: ["normal", "oily", "combination"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "budget", ...e, tags: ["glycolic-acid"] },

  // --- 15 acne treatments ---
  { id: "differin-adapalene-gel", name: "Adapalene Gel 0.1%", brand: "Differin", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", ...e, tags: ["retinoid", "otc"] },
  { id: "larocheposay-effaclar-duo", name: "Effaclar Duo (+) Acne Treatment", brand: "La Roche-Posay", productType: "acne treatment", skinTypes: ["acne-prone", "oily", "combination"], goals: ["acne"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["niacinamide", "texture"] },
  { id: "paulas-choice-clear-bp-treatment", name: "Clear Regular Strength Daily Skin Clearing Treatment 2.5% Benzoyl Peroxide", brand: "Paula's Choice", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy", "benzoyl-peroxide-allergy"], priceTier: "mid-range", ...e, tags: ["benzoyl-peroxide"] },
  { id: "mario-badescu-drying-lotion", name: "Drying Lotion", brand: "Mario Badescu", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["sensitive", "fragrance-sensitive"], priceTier: "budget", ...e, tags: ["spot", "sulfur-calamine"] },
  { id: "neutrogena-rapid-clear-stubborn-acne", name: "Rapid Clear Stubborn Acne Spot Gel", brand: "Neutrogena", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["pregnancy"], priceTier: "budget", ...e, tags: ["benzoyl-peroxide", "spot"] },
  { id: "the-ordinary-salicylic-acid-2", name: "Salicylic Acid 2% Solution", brand: "The Ordinary", productType: "acne treatment", skinTypes: ["oily", "acne-prone"], goals: ["acne", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", ...e, tags: ["salicylic-acid"] },
  { id: "acnefree-terminator-10", name: "Terminator 10 Maximum Strength Acne Spot Treatment", brand: "AcneFree", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["benzoyl-peroxide-allergy"], priceTier: "budget", ...e, tags: ["benzoyl-peroxide", "10-percent"] },
  { id: "kate-somerville-eradikate", name: "EradiKate Acne Treatment", brand: "Kate Somerville", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["sulfur-sensitive"], priceTier: "mid-range", ...e, tags: ["sulfur", "spot"] },
  { id: "peace-out-acne-dots", name: "Acne Healing Dots", brand: "Peace Out", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["hydrocolloid-allergy"], priceTier: "mid-range", ...e, tags: ["hydrocolloid", "salicylic-acid"] },
  { id: "hero-mighty-patch-original", name: "Mighty Patch Original", brand: "Hero Cosmetics", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: [], priceTier: "budget", ...e, tags: ["hydrocolloid", "overnight"] },
  { id: "murad-outsmart-acne", name: "Outsmart Acne Clarifying Treatment", brand: "Murad", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne", "oil-control"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", ...e, tags: ["salicylic-acid", "glycolic-acid"] },
  { id: "clinique-acne-solutions-clinical-gel", name: "Acne Solutions Clinical Clearing Gel", brand: "Clinique", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", ...e, tags: ["salicylic-acid"] },
  { id: "origins-super-spot-remover", name: "Super Spot Remover Blemish Treatment Gel", brand: "Origins", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", ...e, tags: ["salicylic-acid", "spot"] },
  { id: "panoxyl-acne-foaming-wash-10", name: "Acne Foaming Wash Benzoyl Peroxide 10% Maximum Strength", brand: "PanOxyl", productType: "acne treatment", skinTypes: ["acne-prone", "oily", "body"], goals: ["acne"], avoidFor: ["sensitive", "dry"], priceTier: "budget", ...e, tags: ["benzoyl-peroxide", "cleanser"] },
  { id: "larocheposay-effaclar-medicated-wash", name: "Effaclar Medicated Acne Face Wash", brand: "La Roche-Posay", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy"], priceTier: "budget", ...e, tags: ["salicylic-acid", "2-percent"] },

  // --- 15 barrier repair ---
  { id: "cerave-healing-ointment", name: "Healing Ointment", brand: "CeraVe", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair"], avoidFor: ["petrolatum-averse"], priceTier: "budget", ...e, tags: ["petrolatum", "ceramides"] },
  { id: "aquaphor-healing-ointment", name: "Healing Ointment", brand: "Aquaphor", productType: "barrier repair", skinTypes: ["dry", "sensitive", "lips"], goals: ["barrier repair"], avoidFor: ["lanolin-sensitive"], priceTier: "budget", ...e, tags: ["petrolatum", "multi-use"] },
  { id: "eucerin-eczema-relief-cream", name: "Eczema Relief Body Cream", brand: "Eucerin", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", ...e, tags: ["colloidal-oatmeal", "ceramide"] },
  { id: "first-aid-beauty-ultra-repair-ointment", name: "Ultra Repair Ointment", brand: "First Aid Beauty", productType: "barrier repair", skinTypes: ["dry", "sensitive"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["petrolatum", "colloidal-oatmeal"] },
  { id: "larocheposay-cicaplast-baume-b5", name: "Cicaplast Baume B5", brand: "La Roche-Posay", productType: "barrier repair", skinTypes: ["dry", "sensitive", "irritated"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", ...e, tags: ["panthenol", "madecassoside"] },
  { id: "avene-cicalfate-plus", name: "Cicalfate+ Restorative Protective Cream", brand: "Avène", productType: "barrier repair", skinTypes: ["sensitive", "dry", "post-procedure"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["zinc", "copper"] },
  { id: "skinfix-barrier-lipid-peptide-cream", name: "Barrier+ Triple Lipid-Peptide Face Cream", brand: "Skinfix", productType: "barrier repair", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "anti-aging"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["lipids", "peptides"] },
  { id: "drjart-ceramidin-cream", name: "Ceramidin™ Skin Barrier Moisturizing Cream", brand: "Dr. Jart+", productType: "barrier repair", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", ...e, tags: ["ceramide", "panthenol"] },
  { id: "krave-great-barrier-relief", name: "Great Barrier Relief", brand: "Krave Beauty", productType: "barrier repair", skinTypes: ["sensitive", "dry", "combination"], goals: ["barrier repair", "soothing"], avoidFor: ["tamanu-sensitive"], priceTier: "mid-range", ...e, tags: ["tamanu", "ceramide"] },
  { id: "biossance-omega-repair-cream", name: "Squalane + Omega Repair Deep Hydration Moisturizer", brand: "Biossance", productType: "barrier repair", skinTypes: ["dry", "normal", "mature"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["omega-fatty-acids", "squalane"] },
  { id: "elizabeth-arden-eight-hour-cream", name: "Eight Hour® Cream Skin Protectant", brand: "Elizabeth Arden", productType: "barrier repair", skinTypes: ["dry", "normal", "lips"], goals: ["barrier repair"], avoidFor: ["fragrance-sensitive", "lanolin-sensitive"], priceTier: "mid-range", ...e, tags: ["petrolatum", "classic"] },
  { id: "weleda-calendula-face-cream", name: "Calendula Face Cream", brand: "Weleda", productType: "barrier repair", skinTypes: ["dry", "sensitive", "baby-safe"], goals: ["barrier repair", "soothing"], avoidFor: ["essential-oil-sensitive"], priceTier: "budget", ...e, tags: ["calendula", "natural"] },
  { id: "mustela-stelatopia-emollient-cream", name: "Stelatopia Emollient Cream", brand: "Mustela", productType: "barrier repair", skinTypes: ["dry", "eczema-prone", "baby"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["sunflower", "fragrance-free"] },
  { id: "bioderma-atoderm-intensive-balm", name: "Atoderm Intensive Balm", brand: "Bioderma", productType: "barrier repair", skinTypes: ["very-dry", "sensitive", "eczema-prone"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", ...e, tags: ["lipid-complex", "fragrance-free"] },
  { id: "larocheposay-lipikar-balm-ap-plus", name: "Lipikar Balm AP+ Intense Repair Moisturizing Body & Face Cream", brand: "La Roche-Posay", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", ...e, tags: ["ceramide", "niacinamide"] },
];

export const skincareProductCount = skincareProducts.length;
