/**
 * Curated skincare product records for /skincare-checker (not wired to UI yet).
 *
 * TODO: Later move this database to Firebase or CSV import when product count grows to 1000+.
 */

export type SkincareProductType =
  | "moisturizer"
  | "serum"
  | "sunscreen"
  | "cleanser"
  | "toner"
  | "acne treatment"
  | "barrier repair";

export type SkincarePriceTier = "budget" | "mid-range" | "premium";

export type SkincareProduct = {
  id: string;
  name: string;
  brand: string;
  productType: SkincareProductType;
  skinTypes: string[];
  goals: string[];
  avoidFor: string[];
  priceTier: SkincarePriceTier;
  imageUrl: string;
  productUrl: string;
  affiliateSource: string;
  tags: string[];
};

const e = {
  imageUrl: "",
  affiliateSource: "",
} as const;

/** Retailer search URLs — stable when PDP paths or ASINs change. */
function productSearchQuery(brand: string, name: string): string {
  return `${brand} ${name}`.trim();
}

function amazonProductSearch(query: string): string {
  return `https://www.amazon.com/s?k=${encodeURIComponent(query)}`;
}

function sephoraProductSearch(query: string): string {
  return `https://www.sephora.com/search?keyword=${encodeURIComponent(query)}`;
}

function ultaProductSearch(query: string): string {
  return `https://www.ulta.com/search?search=${encodeURIComponent(query)}`;
}

function iherbProductSearch(query: string): string {
  return `https://www.iherb.com/search?kw=${encodeURIComponent(query)}`;
}

export const skincareProducts: SkincareProduct[] = [
  // --- 25 moisturizers ---
  { id: "cerave-moisturizing-cream", name: "Moisturizing Cream", brand: "CeraVe", productType: "moisturizer", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("CeraVe", "Moisturizing Cream")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products-v4/moisturizing-cream/cerave_moisturizing_cream_16oz_jar_front-700x700-v3.jpg?rev=7e37e9cc45754615b1532d77df5a0b52", tags: ["ceramides", "fragrance-free", "mve"] },
  { id: "cerave-daily-moisturizing-lotion", name: "Daily Moisturizing Lotion", brand: "CeraVe", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("CeraVe", "Daily Moisturizing Lotion")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products-v3/daily-moisturizing-lotion/700x700/cerave_daily_moisturizing_lotion_12oz_front_-700x700-v2.jpg?rev=5fb61e1db7fe49fb9faf308c5f583d65", tags: ["ceramides", "lightweight", "fragrance-free"] },
  { id: "vanicream-moisturizing-cream", name: "Moisturizing Cream", brand: "Vanicream", productType: "moisturizer", skinTypes: ["sensitive", "dry"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Vanicream", "Moisturizing Cream")), ...e, imageUrl: "https://www.vanicream.com/dynamic-media/product/images/pump-tc22o-front.jpg?gravity=center&v=galleryMedia&k=u7YL8TUlAAq9Xaxn0U4ApA", tags: ["minimal-ingredients", "eczema-friendly"] },
  { id: "neutrogena-hydro-boost-water-gel", name: "Hydro Boost Water Gel", brand: "Neutrogena", productType: "moisturizer", skinTypes: ["oily", "combination", "normal"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Neutrogena", "Hydro Boost Water Gel")), ...e, imageUrl: "https://images.ctfassets.net/bcjr30vxh6td/3TfmeqVtWAAtF8LobCI3ss/d8071f4fa4a443a928cc00b98c84de95/NTG_USA_US_70501110478_681104748_HB_Hyaluronic_Acid_Water_Gel_Signature_1p7oz_00000.webp?w=800", tags: ["hyaluronic-acid", "gel"] },
  { id: "larocheposay-toleriane-double-repair", name: "Toleriane Double Repair Face Moisturizer", brand: "La Roche-Posay", productType: "moisturizer", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("La Roche-Posay", "Toleriane Double Repair Face Moisturizer")), ...e, imageUrl: "https://media.ulta.com/i/ulta/2509730", tags: ["ceramides", "niacinamide", "fragrance-free"] },
  { id: "first-aid-beauty-ultra-repair-cream", name: "Ultra Repair Cream", brand: "First Aid Beauty", productType: "moisturizer", skinTypes: ["dry", "sensitive"], goals: ["barrier repair", "soothing"], avoidFor: ["eucalyptus-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("First Aid Beauty", "Ultra Repair Cream")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s2935625-main-zoom.jpg", tags: ["colloidal-oatmeal", "rich"] },
  { id: "kiehls-ultra-facial-cream", name: "Ultra Facial Cream with Squalane", brand: "Kiehl's", productType: "moisturizer", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Kiehl's", "Ultra Facial Cream with Squalane")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s2663763-main-zoom.jpg", tags: ["squalane", "glacial-glycoprotein"] },
  { id: "weleda-skin-food-original", name: "Skin Food Original Ultra-Rich Cream", brand: "Weleda", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["barrier repair"], avoidFor: ["essential-oil-sensitive", "fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Weleda", "Skin Food Original Ultra-Rich Cream")), ...e, imageUrl: "", tags: ["botanicals", "rich"] },
  { id: "eucerin-advanced-repair-cream", name: "Advanced Repair Cream", brand: "Eucerin", productType: "moisturizer", skinTypes: ["dry", "very-dry"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Eucerin", "Advanced Repair Cream")), ...e, imageUrl: "", tags: ["urea", "ceramide"] },
  { id: "aveeno-calm-restore-oat-gel", name: "Calm + Restore Oat Gel Moisturizer", brand: "Aveeno", productType: "moisturizer", skinTypes: ["sensitive", "dry"], goals: ["soothing", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Aveeno", "Calm + Restore Oat Gel Moisturizer")), ...e, imageUrl: "https://images.ctfassets.net/mgaihfszrtka/6K6lC4Dwg64DAbYjnlDTph/57ce9c4af1f7e96da2a6888737f4c070/7oz_oobwb-min-en-us-Aveeno?fm=webp&w=800", tags: ["oat", "fragrance-free"] },
  { id: "peter-thomas-roth-water-drench", name: "Water Drench Hyaluronic Cloud Cream", brand: "Peter Thomas Roth", productType: "moisturizer", skinTypes: ["combination", "oily", "normal"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Peter Thomas Roth", "Water Drench Hyaluronic Cloud Cream")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s1898550-main-zoom.jpg", tags: ["hyaluronic-acid", "gel-cream"] },
  { id: "drunk-elephant-protini", name: "Protini Polypeptide Cream", brand: "Drunk Elephant", productType: "moisturizer", skinTypes: ["normal", "combination", "dry"], goals: ["anti-aging", "hydration"], avoidFor: [], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Drunk Elephant", "Protini Polypeptide Cream")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s2025633-main-zoom.jpg", tags: ["peptides", "amino-acids"] },
  { id: "tatcha-the-water-cream", name: "The Water Cream", brand: "Tatcha", productType: "moisturizer", skinTypes: ["oily", "combination", "normal"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Tatcha", "The Water Cream")), ...e, imageUrl: "https://media.ulta.com/i/ulta/2634101", tags: ["japanese-leopard-lily", "oil-free"] },
  { id: "clinique-ddmg", name: "Dramatically Different Moisturizing Gel", brand: "Clinique", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("Clinique", "Dramatically Different Moisturizing Gel")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s789727-main-zoom.jpg", tags: ["oil-free", "gel"] },
  { id: "origins-ginzing-gel", name: "GinZing Energy-Boosting Gel Moisturizer", brand: "Origins", productType: "moisturizer", skinTypes: ["normal", "combination"], goals: ["hydration", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Origins", "GinZing Energy-Boosting Gel Moisturizer")), ...e, imageUrl: "", tags: ["caffeine", "ginseng"] },
  { id: "embryolisse-lait-creme-concentre", name: "Lait-Crème Concentré", brand: "Embryolisse", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: sephoraProductSearch(productSearchQuery("Embryolisse", "Lait-Crème Concentré")), ...e, imageUrl: "", tags: ["multi-use", "makeup-primer"] },
  { id: "nivea-creme", name: "Creme", brand: "Nivea", productType: "moisturizer", skinTypes: ["dry", "normal"], goals: ["barrier repair"], avoidFor: ["fragrance-sensitive", "fungal-acne-prone"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Nivea", "Creme")), ...e, imageUrl: "", tags: ["petrolatum-rich", "classic"] },
  { id: "stratia-liquid-gold", name: "Liquid Gold", brand: "Stratia", productType: "moisturizer", skinTypes: ["dry", "sensitive", "barrier-damaged"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Stratia", "Liquid Gold")), ...e, imageUrl: "", tags: ["ceramides", "cholesterol", "fatty-acids"] },
  { id: "paulas-choice-omega-complex-moisturizer", name: "Omega+ Complex Moisturizer", brand: "Paula's Choice", productType: "moisturizer", skinTypes: ["dry", "normal", "sensitive"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Paula's Choice", "Omega+ Complex Moisturizer")), ...e, imageUrl: "", tags: ["omega-oils", "ceramides"] },
  { id: "belif-aqua-bomb", name: "The True Cream Aqua Bomb", brand: "belif", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("belif", "The True Cream Aqua Bomb")), ...e, imageUrl: "", tags: ["gel-cream", "cooling"] },
  { id: "it-cosmetics-confidence-cream", name: "Confidence in a Cream Hydrating Moisturizer", brand: "IT Cosmetics", productType: "moisturizer", skinTypes: ["dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("IT Cosmetics", "Confidence in a Cream Hydrating Moisturizer")), ...e, imageUrl: "", tags: ["collagen", "peptides"] },
  { id: "yttp-superfood-air-whip", name: "Superfood Air-Whip Moisture Cream", brand: "Youth To The People", productType: "moisturizer", skinTypes: ["combination", "normal"], goals: ["hydration"], avoidFor: ["essential-oil-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Youth To The People", "Superfood Air-Whip Moisture Cream")), ...e, imageUrl: "", tags: ["kale", "spinach", "hyaluronic-acid"] },
  { id: "glow-recipe-plum-plump-cream", name: "Plum Plump Hyaluronic Cream", brand: "Glow Recipe", productType: "moisturizer", skinTypes: ["normal", "combination", "dry"], goals: ["hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Glow Recipe", "Plum Plump Hyaluronic Cream")), ...e, imageUrl: "", tags: ["plum", "hyaluronic-acid"] },
  { id: "summer-fridays-cloud-dew", name: "Cloud Dew Oil-Free Gel Cream Moisturizer", brand: "Summer Fridays", productType: "moisturizer", skinTypes: ["oily", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Summer Fridays", "Cloud Dew Oil-Free Gel Cream Moisturizer")), ...e, imageUrl: "", tags: ["oil-free", "amino-acids"] },
  { id: "olay-regenerist-micro-sculpting-cream", name: "Regenerist Micro-Sculpting Cream", brand: "Olay", productType: "moisturizer", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Olay", "Regenerist Micro-Sculpting Cream")), ...e, imageUrl: "", tags: ["niacinamide", "peptides"] },

  // --- 20 sunscreens ---
  { id: "eltamd-uv-clear-spf46", name: "UV Clear Broad-Spectrum SPF 46", brand: "EltaMD", productType: "sunscreen", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["oil-control", "sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("EltaMD", "UV Clear Broad-Spectrum SPF 46")), ...e, imageUrl: "https://eltamd.com/cdn/shop/files/UV_Clear_SPF_46_02500A_With_award_1200x1200.jpg?v=1773888112", tags: ["mineral-leaning", "niacinamide", "dermatologist-favorite"] },
  { id: "larocheposay-anthelios-melt-in-milk-spf60", name: "Anthelios Melt-in Milk Sunscreen SPF 60", brand: "La Roche-Posay", productType: "sunscreen", skinTypes: ["normal", "dry", "sensitive"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("La Roche-Posay", "Anthelios Melt-in Milk Sunscreen SPF 60")), ...e, imageUrl: "https://media.ulta.com/i/ulta/2236414", tags: ["broad-spectrum", "water-resistant"] },
  { id: "supergoop-unseen-sunscreen-spf40", name: "Unseen Sunscreen SPF 40", brand: "Supergoop", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: ["silicone-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Supergoop", "Unseen Sunscreen SPF 40")), ...e, imageUrl: "https://cdn.shopify.com/s/files/1/1503/5658/files/Unseen_PDP_1180x1604_5d03ff64-0ed3-4fbb-8bef-c6b7dfbaa0bd.png?v=1774797043", tags: ["chemical", "primer-feel"] },
  { id: "cerave-hydrating-mineral-spf30", name: "Hydrating Mineral Sunscreen SPF 30", brand: "CeraVe", productType: "sunscreen", skinTypes: ["sensitive", "dry", "normal"], goals: ["sun protection", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("CeraVe", "Hydrating Mineral Sunscreen SPF 30")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/sunscreen/face/30-spf-face/30-spf-face_front.jpg?rev=3a662171cf3d47eea33f18a9d080b1a8", tags: ["mineral", "ceramides"] },
  { id: "neutrogena-ultra-sheer-spf55", name: "Ultra Sheer Dry-Touch Sunscreen SPF 55", brand: "Neutrogena", productType: "sunscreen", skinTypes: ["normal", "oily", "combination"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Neutrogena", "Ultra Sheer Dry-Touch Sunscreen SPF 55")), ...e, imageUrl: "", tags: ["chemical", "dry-touch"] },
  { id: "australian-gold-botanical-tinted-spf50", name: "Botanical Tinted Face Sunscreen SPF 50", brand: "Australian Gold", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Australian Gold", "Botanical Tinted Face Sunscreen SPF 50")), ...e, imageUrl: "", tags: ["mineral", "tinted"] },
  { id: "isdin-eryfotona-actinica-spf50", name: "Eryfotona Actinica Mineral Sunscreen SPF 50+", brand: "ISDIN", productType: "sunscreen", skinTypes: ["normal", "dry", "mature"], goals: ["sun protection", "anti-aging"], avoidFor: [], priceTier: "premium", productUrl: amazonProductSearch(productSearchQuery("ISDIN", "Eryfotona Actinica Mineral Sunscreen SPF 50+")), ...e, imageUrl: "", tags: ["mineral", "dna-repairosomes"] },
  { id: "blue-lizard-sensitive-mineral-spf50", name: "Sensitive Mineral Sunscreen SPF 50+", brand: "Blue Lizard", productType: "sunscreen", skinTypes: ["sensitive", "children"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Blue Lizard", "Sensitive Mineral Sunscreen SPF 50+")), ...e, imageUrl: "", tags: ["mineral", "reef-conscious-line"] },
  { id: "cosrx-aloe-soothing-sun-cream-spf50", name: "Aloe Soothing Sun Cream SPF 50 PA+++", brand: "COSRX", productType: "sunscreen", skinTypes: ["dry", "sensitive", "normal"], goals: ["sun protection", "soothing"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("COSRX", "Aloe Soothing Sun Cream SPF 50 PA+++")), ...e, imageUrl: "", tags: ["chemical", "aloe"] },
  { id: "beauty-of-joseon-relief-sun-spf50", name: "Relief Sun Rice + Probiotics SPF 50+ PA++++", brand: "Beauty of Joseon", productType: "sunscreen", skinTypes: ["normal", "dry", "sensitive"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Beauty of Joseon", "Relief Sun Rice + Probiotics SPF 50+ PA++++")), ...e, imageUrl: "", tags: ["chemical", "rice"] },
  { id: "skin-aqua-tone-up-uv-essence", name: "Tone Up UV Essence SPF 50+ PA++++", brand: "Skin Aqua", productType: "sunscreen", skinTypes: ["normal", "combination"], goals: ["sun protection", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Skin Aqua", "Tone Up UV Essence SPF 50+ PA++++")), ...e, imageUrl: "", tags: ["japanese", "tone-up"] },
  { id: "canmake-mermaid-skin-gel-uv", name: "Mermaid Skin Gel UV SPF 50+ PA++++", brand: "Canmake", productType: "sunscreen", skinTypes: ["normal", "oily", "combination"], goals: ["sun protection"], avoidFor: ["alcohol-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Canmake", "Mermaid Skin Gel UV SPF 50+ PA++++")), ...e, imageUrl: "", tags: ["gel", "japanese"] },
  { id: "black-girl-sunscreen-spf30", name: "Make Me Invisible SPF 30", brand: "Black Girl Sunscreen", productType: "sunscreen", skinTypes: ["all", "deeper-skin-tones"], goals: ["sun protection"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Black Girl Sunscreen", "Make Me Invisible SPF 30")), ...e, imageUrl: "", tags: ["no-white-cast-focus", "broad-spectrum"] },
  { id: "shiseido-ultimate-sun-protector-spf50", name: "Ultimate Sun Protector Cream SPF 50+ WetForce", brand: "Shiseido", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Shiseido", "Ultimate Sun Protector Cream SPF 50+ WetForce")), ...e, imageUrl: "", tags: ["wetforce", "synchroshield"] },
  { id: "drunk-elephant-umbra-sheer-spf30", name: "Umbra Sheer Physical Daily Defense SPF 30", brand: "Drunk Elephant", productType: "sunscreen", skinTypes: ["sensitive", "normal"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Drunk Elephant", "Umbra Sheer Physical Daily Defense SPF 30")), ...e, imageUrl: "", tags: ["mineral", "marula"] },
  { id: "biossance-squalane-zinc-spf30", name: "Squalane + Zinc Sheer Mineral Sunscreen SPF 30 PA +++", brand: "Biossance", productType: "sunscreen", skinTypes: ["sensitive", "dry", "normal"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Biossance", "Squalane + Zinc Sheer Mineral Sunscreen SPF 30 PA +++")), ...e, imageUrl: "", tags: ["mineral", "squalane"] },
  { id: "sun-bum-original-spf50", name: "Original SPF 50 Sunscreen Lotion", brand: "Sun Bum", productType: "sunscreen", skinTypes: ["normal", "body"], goals: ["sun protection"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Sun Bum", "Original SPF 50 Sunscreen Lotion")), ...e, imageUrl: "", tags: ["coconut-scent", "broad-spectrum"] },
  { id: "aveeno-protect-hydrate-spf60", name: "Protect + Hydrate Sunscreen Broad Spectrum SPF 60", brand: "Aveeno", productType: "sunscreen", skinTypes: ["dry", "normal"], goals: ["sun protection", "hydration"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Aveeno", "Protect + Hydrate Sunscreen Broad Spectrum SPF 60")), ...e, imageUrl: "", tags: ["oat", "chemical"] },
  { id: "paulas-choice-youth-extending-fluid-spf50", name: "Youth-Extending Daily Hydrating Fluid SPF 50", brand: "Paula's Choice", productType: "sunscreen", skinTypes: ["normal", "combination", "oily"], goals: ["sun protection", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Paula's Choice", "Youth-Extending Daily Hydrating Fluid SPF 50")), ...e, imageUrl: "", tags: ["antioxidants", "fluid"] },
  { id: "tower28-sunnydays-spf30", name: "SunnyDays SPF 30 Tinted Sunscreen Foundation", brand: "Tower 28", productType: "sunscreen", skinTypes: ["sensitive", "normal", "combination"], goals: ["sun protection"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Tower 28", "SunnyDays SPF 30 Tinted Sunscreen Foundation")), ...e, imageUrl: "", tags: ["tinted", "national-eczema-association-seal"] },

  // --- 20 serums ---
  { id: "the-ordinary-niacinamide-zinc", name: "Niacinamide 10% + Zinc 1%", brand: "The Ordinary", productType: "serum", skinTypes: ["oily", "acne-prone", "combination"], goals: ["oil-control", "pore appearance"], avoidFor: [], priceTier: "budget", productUrl: sephoraProductSearch(productSearchQuery("The Ordinary", "Niacinamide 10% + Zinc 1%")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s2031391-main-zoom.jpg", tags: ["niacinamide", "zinc"] },
  { id: "skinceuticals-ce-ferulic", name: "C E Ferulic", brand: "SkinCeuticals", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "brightening"], avoidFor: ["vitamin-c-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("SkinCeuticals", "C E Ferulic")), ...e, imageUrl: "", tags: ["vitamin-c", "vitamin-e", "ferulic-acid"] },
  { id: "drunk-elephant-tlc-framboos", name: "T.L.C. Framboos Glycolic Resurfacing Night Serum", brand: "Drunk Elephant", productType: "serum", skinTypes: ["normal", "combination", "oily"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Drunk Elephant", "T.L.C. Framboos Glycolic Resurfacing Night Serum")), ...e, imageUrl: "", tags: ["aha", "bha", "blend"] },
  { id: "esteelauder-advanced-night-repair", name: "Advanced Night Repair Synchronized Multi-Recovery Complex", brand: "Estée Lauder", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Estée Lauder", "Advanced Night Repair Synchronized Multi-Recovery Complex")), ...e, imageUrl: "", tags: ["hyaluronic-acid", "bifida"] },
  { id: "lancome-genifique", name: "Advanced Génifique Youth Activating Serum", brand: "Lancôme", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Lancôme", "Advanced Génifique Youth Activating Serum")), ...e, imageUrl: "", tags: ["prebiotic", "hyaluronic-acid"] },
  { id: "olay-regenerist-micro-sculpting-serum", name: "Regenerist Micro-Sculpting Serum", brand: "Olay", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Olay", "Regenerist Micro-Sculpting Serum")), ...e, imageUrl: "", tags: ["niacinamide", "peptides"] },
  { id: "the-ordinary-ha-b5", name: "Hyaluronic Acid 2% + B5", brand: "The Ordinary", productType: "serum", skinTypes: ["dry", "normal", "combination"], goals: ["hydration"], avoidFor: [], priceTier: "budget", productUrl: sephoraProductSearch(productSearchQuery("The Ordinary", "Hyaluronic Acid 2% + B5")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s2735140-main-zoom.jpg", tags: ["hyaluronic-acid", "panthenol"] },
  { id: "paulas-choice-azelaic-acid-booster", name: "10% Azelaic Acid Booster", brand: "Paula's Choice", productType: "serum", skinTypes: ["acne-prone", "sensitive", "combination"], goals: ["brightening", "texture"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Paula's Choice", "10% Azelaic Acid Booster")), ...e, imageUrl: "", tags: ["azelaic-acid", "salicylic-acid"] },
  { id: "good-molecules-niacinamide-serum", name: "Niacinamide Serum", brand: "Good Molecules", productType: "serum", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "brightening"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Good Molecules", "Niacinamide Serum")), ...e, imageUrl: "", tags: ["niacinamide"] },
  { id: "vichy-mineral-89", name: "Minéral 89 Hyaluronic Acid Face Serum", brand: "Vichy", productType: "serum", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "barrier repair"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Vichy", "Minéral 89 Hyaluronic Acid Face Serum")), ...e, imageUrl: "", tags: ["volcanic-water", "hyaluronic-acid"] },
  { id: "kiehls-midnight-recovery", name: "Midnight Recovery Concentrate Face Oil", brand: "Kiehl's", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["essential-oil-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Kiehl's", "Midnight Recovery Concentrate Face Oil")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s1988732-main-zoom.jpg", tags: ["evening-primrose", "lavender-oil"] },
  { id: "biossance-vitamin-c-dark-spot", name: "Squalane + Vitamin C Dark Spot Serum", brand: "Biossance", productType: "serum", skinTypes: ["normal", "combination", "dry"], goals: ["brightening", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Biossance", "Squalane + Vitamin C Dark Spot Serum")), ...e, imageUrl: "", tags: ["vitamin-c-derivative", "squalane"] },
  { id: "sunday-riley-good-genes", name: "Good Genes All-In-One Lactic Acid Treatment", brand: "Sunday Riley", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Sunday Riley", "Good Genes All-In-One Lactic Acid Treatment")), ...e, imageUrl: "", tags: ["lactic-acid"] },
  { id: "larocheposay-pure-vitamin-c10", name: "Pure Vitamin C10 Serum", brand: "La Roche-Posay", productType: "serum", skinTypes: ["normal", "combination"], goals: ["brightening"], avoidFor: ["vitamin-c-sensitive"], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("La Roche-Posay", "Pure Vitamin C10 Serum")), ...e, imageUrl: "", tags: ["vitamin-c", "salicylic-acid"] },
  { id: "versed-press-restart-retinol", name: "Press Restart Gentle Retinol Serum", brand: "Versed", productType: "serum", skinTypes: ["normal", "combination", "mature"], goals: ["anti-aging", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Versed", "Press Restart Gentle Retinol Serum")), ...e, imageUrl: "", tags: ["retinol", "bakuchiol"] },
  { id: "glow-recipe-watermelon-dew-drops", name: "Watermelon Glow Niacinamide Dew Drops", brand: "Glow Recipe", productType: "serum", skinTypes: ["normal", "dry", "combination"], goals: ["brightening", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Glow Recipe", "Watermelon Glow Niacinamide Dew Drops")), ...e, imageUrl: "", tags: ["niacinamide", "highlight"] },
  { id: "innisfree-green-tea-seed-serum", name: "Green Tea Seed Hyaluronic Serum", brand: "innisfree", productType: "serum", skinTypes: ["normal", "combination", "dry"], goals: ["hydration", "antioxidant"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("innisfree", "Green Tea Seed Hyaluronic Serum")), ...e, imageUrl: "", tags: ["green-tea", "hyaluronic-acid"] },
  { id: "sulwhasoo-first-care-activating-serum", name: "First Care Activating Serum VI", brand: "Sulwhasoo", productType: "serum", skinTypes: ["dry", "normal", "mature"], goals: ["hydration", "anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Sulwhasoo", "First Care Activating Serum VI")), ...e, imageUrl: "", tags: ["hanbang", "jaum"] },
  { id: "lancome-genifique-light-pearl", name: "Advanced Génifique Yeux Light-Pearl Eye & Lash Serum", brand: "Lancôme", productType: "serum", skinTypes: ["normal", "mature"], goals: ["anti-aging"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Lancôme", "Advanced Génifique Yeux Light-Pearl Eye & Lash Serum")), ...e, imageUrl: "", tags: ["eye", "lash"] },
  { id: "the-ordinary-buffet-copper", name: "Buffet + Copper Peptides 1%", brand: "The Ordinary", productType: "serum", skinTypes: ["normal", "dry", "mature"], goals: ["anti-aging"], avoidFor: ["vitamin-c-stacking"], priceTier: "budget", productUrl: sephoraProductSearch(productSearchQuery("The Ordinary", "Buffet + Copper Peptides 1%")), ...e, imageUrl: "", tags: ["peptides", "copper"] },

  // --- 15 cleansers ---
  { id: "cerave-hydrating-cleanser", name: "Hydrating Facial Cleanser", brand: "CeraVe", productType: "cleanser", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("CeraVe", "Hydrating Facial Cleanser")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/cleansers/hydrating-facial-cleanser/photos/2022/700x700/cerave_daily_hydrating-cleanser_12oz_front-700x700-v2.jpg?rev=8dcf681b75c042deaaa0c6ea1581d4df", tags: ["ceramides", "non-foaming"] },
  { id: "cerave-foaming-cleanser", name: "Foaming Facial Cleanser", brand: "CeraVe", productType: "cleanser", skinTypes: ["oily", "combination", "normal"], goals: ["oil-control", "gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("CeraVe", "Foaming Facial Cleanser")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products-v3/foaming-facial-cleanser/700x700/cerave_foaming-facial-cleanser-12oz_front-700x700-v2.jpg?rev=da10428fc5104c97a980e0d5ff5ce9bb", tags: ["niacinamide", "ceramides"] },
  { id: "larocheposay-toleriane-gentle-cleanser", name: "Toleriane Hydrating Gentle Cleanser", brand: "La Roche-Posay", productType: "cleanser", skinTypes: ["dry", "sensitive"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("La Roche-Posay", "Toleriane Hydrating Gentle Cleanser")), ...e, imageUrl: "", tags: ["cream", "fragrance-free"] },
  { id: "vanicream-gentle-facial-cleanser", name: "Gentle Facial Cleanser", brand: "Vanicream", productType: "cleanser", skinTypes: ["sensitive", "dry"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Vanicream", "Gentle Facial Cleanser")), ...e, imageUrl: "https://www.vanicream.com/dynamic-media/product/images/gentle-facial-cleanser-8-oz-front.jpg?gravity=center&v=galleryMedia&k=wpsSDw6D4yetnnA15I28ig", tags: ["minimal", "gluten-free"] },
  { id: "fresh-soy-face-cleanser", name: "Soy Face Cleanser", brand: "Fresh", productType: "cleanser", skinTypes: ["normal", "dry", "sensitive"], goals: ["gentle-cleanse", "hydration"], avoidFor: ["soy-allergy"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Fresh", "Soy Face Cleanser")), ...e, imageUrl: "", tags: ["soy", "amino-acids"] },
  { id: "yttp-superfood-cleanser", name: "Superfood Antioxidant Cleanser", brand: "Youth To The People", productType: "cleanser", skinTypes: ["normal", "combination", "oily"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Youth To The People", "Superfood Antioxidant Cleanser")), ...e, imageUrl: "", tags: ["kale", "spinach", "gel"] },
  { id: "neutrogena-fresh-foaming-cleanser", name: "Fresh Foaming Cleanser", brand: "Neutrogena", productType: "cleanser", skinTypes: ["normal", "combination"], goals: ["makeup-removal"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Neutrogena", "Fresh Foaming Cleanser")), ...e, imageUrl: "", tags: ["foaming"] },
  { id: "cosrx-low-ph-good-morning", name: "Low pH Good Morning Gel Cleanser", brand: "COSRX", productType: "cleanser", skinTypes: ["oily", "combination", "acne-prone"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("COSRX", "Low pH Good Morning Gel Cleanser")), ...e, imageUrl: "", tags: ["low-ph", "bha"] },
  { id: "krave-matcha-hemp-cleanser", name: "Matcha Hemp Hydrating Cleanser", brand: "Krave Beauty", productType: "cleanser", skinTypes: ["normal", "dry", "combination"], goals: ["hydration", "gentle-cleanse"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Krave Beauty", "Matcha Hemp Hydrating Cleanser")), ...e, imageUrl: "", tags: ["matcha", "hemp"] },
  { id: "paulas-choice-resist-hydrating-cleanser", name: "RESIST Optimal Results Hydrating Cleanser", brand: "Paula's Choice", productType: "cleanser", skinTypes: ["dry", "normal", "sensitive"], goals: ["gentle-cleanse", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Paula's Choice", "RESIST Optimal Results Hydrating Cleanser")), ...e, imageUrl: "", tags: ["cream", "antioxidants"] },
  { id: "kiehls-ultra-facial-cleanser", name: "Ultra Facial Cleanser", brand: "Kiehl's", productType: "cleanser", skinTypes: ["normal", "combination", "dry"], goals: ["gentle-cleanse"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Kiehl's", "Ultra Facial Cleanser")), ...e, imageUrl: "", tags: ["squalane", "apricot-kernel"] },
  { id: "glossier-milky-jelly-cleanser", name: "Milky Jelly Cleanser", brand: "Glossier", productType: "cleanser", skinTypes: ["normal", "dry", "sensitive"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Glossier", "Milky Jelly Cleanser")), ...e, imageUrl: "", tags: ["allantoin", "pro-vitamin-b5"] },
  { id: "innisfree-green-tea-foam-cleanser", name: "Green Tea Hyaluronic Acid Hydrating Foam Cleanser", brand: "innisfree", productType: "cleanser", skinTypes: ["normal", "combination", "oily"], goals: ["hydration", "gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "budget", productUrl: sephoraProductSearch(productSearchQuery("innisfree", "Green Tea Hyaluronic Acid Hydrating Foam Cleanser")), ...e, imageUrl: "", tags: ["green-tea", "foam"] },
  { id: "dhc-deep-cleansing-oil", name: "Deep Cleansing Oil", brand: "DHC", productType: "cleanser", skinTypes: ["dry", "normal", "combination"], goals: ["makeup-removal"], avoidFor: ["olive-oil-sensitive"], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("DHC", "Deep Cleansing Oil")), ...e, imageUrl: "", tags: ["oil-cleanser", "double-cleanse"] },
  { id: "tatcha-rice-wash", name: "The Rice Wash Skin-Softening Cleanser", brand: "Tatcha", productType: "cleanser", skinTypes: ["normal", "dry", "combination"], goals: ["gentle-cleanse"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("Tatcha", "The Rice Wash Skin-Softening Cleanser")), ...e, imageUrl: "", tags: ["rice", "ph-neutral"] },

  // --- 10 toners / essences ---
  { id: "laneige-cream-skin-refiner", name: "Cream Skin Cerapeptide™ Toner & Moisturizer", brand: "Laneige", productType: "toner", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "barrier repair"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Laneige", "Cream Skin Cerapeptide™ Toner & Moisturizer")), ...e, imageUrl: "", tags: ["ceramide", "milky-toner"] },
  { id: "cosrx-snail-96-essence", name: "Advanced Snail 96 Mucin Power Essence", brand: "COSRX", productType: "toner", skinTypes: ["dry", "normal", "sensitive"], goals: ["hydration", "barrier repair"], avoidFor: ["snail-allergy"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("COSRX", "Advanced Snail 96 Mucin Power Essence")), ...e, imageUrl: "", tags: ["snail-mucin", "essence"] },
  { id: "missha-time-revolution-essence-5x", name: "Time Revolution The First Essence 5X", brand: "Missha", productType: "toner", skinTypes: ["normal", "dry", "mature"], goals: ["hydration", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: iherbProductSearch(productSearchQuery("Missha", "Time Revolution The First Essence 5X")), ...e, imageUrl: "", tags: ["fermented", "first-essence"] },
  { id: "sk-ii-facial-treatment-essence", name: "Facial Treatment Essence", brand: "SK-II", productType: "toner", skinTypes: ["normal", "combination", "mature"], goals: ["texture", "brightening"], avoidFor: ["fragrance-sensitive"], priceTier: "premium", productUrl: sephoraProductSearch(productSearchQuery("SK-II", "Facial Treatment Essence")), ...e, imageUrl: "", tags: ["pitera", "fermented"] },
  { id: "paulas-choice-2-bha-liquid", name: "Skin Perfecting 2% BHA Liquid Exfoliant", brand: "Paula's Choice", productType: "toner", skinTypes: ["oily", "acne-prone", "combination"], goals: ["texture", "pores"], avoidFor: ["pregnancy", "sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Paula's Choice", "Skin Perfecting 2% BHA Liquid Exfoliant")), ...e, imageUrl: "https://www.sephora.com/productimages/sku/s2421360-main-zoom.jpg", tags: ["salicylic-acid", "leave-on"] },
  { id: "pyunkang-yul-essence-toner", name: "Essence Toner", brand: "Pyunkang Yul", productType: "toner", skinTypes: ["dry", "sensitive", "normal"], goals: ["hydration", "soothing"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Pyunkang Yul", "Essence Toner")), ...e, imageUrl: "", tags: ["minimal", "astringent-free"] },
  { id: "thayers-alcohol-free-toner", name: "Alcohol-Free Witch Hazel Facial Toner", brand: "Thayers", productType: "toner", skinTypes: ["normal", "combination", "oily"], goals: ["oil-control"], avoidFor: ["witch-hazel-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Thayers", "Alcohol-Free Witch Hazel Facial Toner")), ...e, imageUrl: "", tags: ["witch-hazel", "aloe"] },
  { id: "dickinsons-enhanced-witch-hazel-toner", name: "Enhanced Witch Hazel Hydrating Toner", brand: "Dickinson's", productType: "toner", skinTypes: ["normal", "combination"], goals: ["hydration"], avoidFor: ["witch-hazel-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Dickinson's", "Enhanced Witch Hazel Hydrating Toner")), ...e, imageUrl: "", tags: ["witch-hazel", "hyaluronic-acid"] },
  { id: "hada-labo-gokujyun-lotion-moist", name: "Gokujyun Hyaluronic Acid Lotion (Moist)", brand: "Hada Labo", productType: "toner", skinTypes: ["dry", "normal"], goals: ["hydration"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Hada Labo", "Gokujyun Hyaluronic Acid Lotion (Moist)")), ...e, imageUrl: "", tags: ["hyaluronic-acid", "japanese"] },
  { id: "mario-badescu-glycolic-acid-toner", name: "Glycolic Acid Toner", brand: "Mario Badescu", productType: "toner", skinTypes: ["normal", "oily", "combination"], goals: ["texture", "brightening"], avoidFor: ["sensitive", "pregnancy"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Mario Badescu", "Glycolic Acid Toner")), ...e, imageUrl: "", tags: ["glycolic-acid"] },

  // --- 15 acne treatments ---
  { id: "differin-adapalene-gel", name: "Adapalene Gel 0.1%", brand: "Differin", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Differin", "Adapalene Gel 0.1%")), ...e, imageUrl: "", tags: ["retinoid", "otc"] },
  { id: "larocheposay-effaclar-duo", name: "Effaclar Duo (+) Acne Treatment", brand: "La Roche-Posay", productType: "acne treatment", skinTypes: ["acne-prone", "oily", "combination"], goals: ["acne"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("La Roche-Posay", "Effaclar Duo (+) Acne Treatment")), ...e, imageUrl: "", tags: ["niacinamide", "texture"] },
  { id: "paulas-choice-clear-bp-treatment", name: "Clear Regular Strength Daily Skin Clearing Treatment 2.5% Benzoyl Peroxide", brand: "Paula's Choice", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy", "benzoyl-peroxide-allergy"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Paula's Choice", "Clear Regular Strength Daily Skin Clearing Treatment 2.5% Benzoyl Peroxide")), ...e, imageUrl: "", tags: ["benzoyl-peroxide"] },
  { id: "mario-badescu-drying-lotion", name: "Drying Lotion", brand: "Mario Badescu", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["sensitive", "fragrance-sensitive"], priceTier: "budget", productUrl: ultaProductSearch(productSearchQuery("Mario Badescu", "Drying Lotion")), ...e, imageUrl: "", tags: ["spot", "sulfur-calamine"] },
  { id: "neutrogena-rapid-clear-stubborn-acne", name: "Rapid Clear Stubborn Acne Spot Gel", brand: "Neutrogena", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["pregnancy"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Neutrogena", "Rapid Clear Stubborn Acne Spot Gel")), ...e, imageUrl: "", tags: ["benzoyl-peroxide", "spot"] },
  { id: "the-ordinary-salicylic-acid-2", name: "Salicylic Acid 2% Solution", brand: "The Ordinary", productType: "acne treatment", skinTypes: ["oily", "acne-prone"], goals: ["acne", "texture"], avoidFor: ["pregnancy", "sensitive"], priceTier: "budget", productUrl: sephoraProductSearch(productSearchQuery("The Ordinary", "Salicylic Acid 2% Solution")), ...e, imageUrl: "", tags: ["salicylic-acid"] },
  { id: "acnefree-terminator-10", name: "Terminator 10 Maximum Strength Acne Spot Treatment", brand: "AcneFree", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["benzoyl-peroxide-allergy"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("AcneFree", "Terminator 10 Maximum Strength Acne Spot Treatment")), ...e, imageUrl: "", tags: ["benzoyl-peroxide", "10-percent"] },
  { id: "kate-somerville-eradikate", name: "EradiKate Acne Treatment", brand: "Kate Somerville", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["sulfur-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Kate Somerville", "EradiKate Acne Treatment")), ...e, imageUrl: "", tags: ["sulfur", "spot"] },
  { id: "peace-out-acne-dots", name: "Acne Healing Dots", brand: "Peace Out", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["hydrocolloid-allergy"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Peace Out", "Acne Healing Dots")), ...e, imageUrl: "", tags: ["hydrocolloid", "salicylic-acid"] },
  { id: "hero-mighty-patch-original", name: "Mighty Patch Original", brand: "Hero Cosmetics", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Hero Cosmetics", "Mighty Patch Original")), ...e, imageUrl: "", tags: ["hydrocolloid", "overnight"] },
  { id: "murad-outsmart-acne", name: "Outsmart Acne Clarifying Treatment", brand: "Murad", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne", "oil-control"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Murad", "Outsmart Acne Clarifying Treatment")), ...e, imageUrl: "", tags: ["salicylic-acid", "glycolic-acid"] },
  { id: "clinique-acne-solutions-clinical-gel", name: "Acne Solutions Clinical Clearing Gel", brand: "Clinique", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", productUrl: ultaProductSearch(productSearchQuery("Clinique", "Acne Solutions Clinical Clearing Gel")), ...e, imageUrl: "", tags: ["salicylic-acid"] },
  { id: "origins-super-spot-remover", name: "Super Spot Remover Blemish Treatment Gel", brand: "Origins", productType: "acne treatment", skinTypes: ["acne-prone"], goals: ["acne"], avoidFor: ["salicylic-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Origins", "Super Spot Remover Blemish Treatment Gel")), ...e, imageUrl: "", tags: ["salicylic-acid", "spot"] },
  { id: "panoxyl-acne-foaming-wash-10", name: "Acne Foaming Wash Benzoyl Peroxide 10% Maximum Strength", brand: "PanOxyl", productType: "acne treatment", skinTypes: ["acne-prone", "oily", "body"], goals: ["acne"], avoidFor: ["sensitive", "dry"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("PanOxyl", "Acne Foaming Wash Benzoyl Peroxide 10% Maximum Strength")), ...e, imageUrl: "", tags: ["benzoyl-peroxide", "cleanser"] },
  { id: "larocheposay-effaclar-medicated-wash", name: "Effaclar Medicated Acne Face Wash", brand: "La Roche-Posay", productType: "acne treatment", skinTypes: ["acne-prone", "oily"], goals: ["acne"], avoidFor: ["pregnancy"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("La Roche-Posay", "Effaclar Medicated Acne Face Wash")), ...e, imageUrl: "", tags: ["salicylic-acid", "2-percent"] },

  // --- 15 barrier repair ---
  { id: "cerave-healing-ointment", name: "Healing Ointment", brand: "CeraVe", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair"], avoidFor: ["petrolatum-averse"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("CeraVe", "Healing Ointment")), ...e, imageUrl: "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/moisturizers/healing-ointment/2025/healing-ointment_front.jpg?rev=c41d50fa05b34fa59e5affe3b389b681", tags: ["petrolatum", "ceramides"] },
  { id: "aquaphor-healing-ointment", name: "Healing Ointment", brand: "Aquaphor", productType: "barrier repair", skinTypes: ["dry", "sensitive", "lips"], goals: ["barrier repair"], avoidFor: ["lanolin-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Aquaphor", "Healing Ointment")), ...e, imageUrl: "", tags: ["petrolatum", "multi-use"] },
  { id: "eucerin-eczema-relief-cream", name: "Eczema Relief Body Cream", brand: "Eucerin", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Eucerin", "Eczema Relief Body Cream")), ...e, imageUrl: "", tags: ["colloidal-oatmeal", "ceramide"] },
  { id: "first-aid-beauty-ultra-repair-ointment", name: "Ultra Repair Ointment", brand: "First Aid Beauty", productType: "barrier repair", skinTypes: ["dry", "sensitive"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("First Aid Beauty", "Ultra Repair Ointment")), ...e, imageUrl: "", tags: ["petrolatum", "colloidal-oatmeal"] },
  { id: "larocheposay-cicaplast-baume-b5", name: "Cicaplast Baume B5", brand: "La Roche-Posay", productType: "barrier repair", skinTypes: ["dry", "sensitive", "irritated"], goals: ["barrier repair", "soothing"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("La Roche-Posay", "Cicaplast Baume B5")), ...e, imageUrl: "", tags: ["panthenol", "madecassoside"] },
  { id: "avene-cicalfate-plus", name: "Cicalfate+ Restorative Protective Cream", brand: "Avène", productType: "barrier repair", skinTypes: ["sensitive", "dry", "post-procedure"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Avène", "Cicalfate+ Restorative Protective Cream")), ...e, imageUrl: "", tags: ["zinc", "copper"] },
  { id: "skinfix-barrier-lipid-peptide-cream", name: "Barrier+ Triple Lipid-Peptide Face Cream", brand: "Skinfix", productType: "barrier repair", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "anti-aging"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Skinfix", "Barrier+ Triple Lipid-Peptide Face Cream")), ...e, imageUrl: "", tags: ["lipids", "peptides"] },
  { id: "drjart-ceramidin-cream", name: "Ceramidin™ Skin Barrier Moisturizing Cream", brand: "Dr. Jart+", productType: "barrier repair", skinTypes: ["dry", "sensitive", "normal"], goals: ["barrier repair", "hydration"], avoidFor: ["fragrance-sensitive"], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Dr. Jart+", "Ceramidin™ Skin Barrier Moisturizing Cream")), ...e, imageUrl: "", tags: ["ceramide", "panthenol"] },
  { id: "krave-great-barrier-relief", name: "Great Barrier Relief", brand: "Krave Beauty", productType: "barrier repair", skinTypes: ["sensitive", "dry", "combination"], goals: ["barrier repair", "soothing"], avoidFor: ["tamanu-sensitive"], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Krave Beauty", "Great Barrier Relief")), ...e, imageUrl: "", tags: ["tamanu", "ceramide"] },
  { id: "biossance-omega-repair-cream", name: "Squalane + Omega Repair Deep Hydration Moisturizer", brand: "Biossance", productType: "barrier repair", skinTypes: ["dry", "normal", "mature"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "mid-range", productUrl: sephoraProductSearch(productSearchQuery("Biossance", "Squalane + Omega Repair Deep Hydration Moisturizer")), ...e, imageUrl: "", tags: ["omega-fatty-acids", "squalane"] },
  { id: "elizabeth-arden-eight-hour-cream", name: "Eight Hour® Cream Skin Protectant", brand: "Elizabeth Arden", productType: "barrier repair", skinTypes: ["dry", "normal", "lips"], goals: ["barrier repair"], avoidFor: ["fragrance-sensitive", "lanolin-sensitive"], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Elizabeth Arden", "Eight Hour® Cream Skin Protectant")), ...e, imageUrl: "", tags: ["petrolatum", "classic"] },
  { id: "weleda-calendula-face-cream", name: "Calendula Face Cream", brand: "Weleda", productType: "barrier repair", skinTypes: ["dry", "sensitive", "baby-safe"], goals: ["barrier repair", "soothing"], avoidFor: ["essential-oil-sensitive"], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("Weleda", "Calendula Face Cream")), ...e, imageUrl: "", tags: ["calendula", "natural"] },
  { id: "mustela-stelatopia-emollient-cream", name: "Stelatopia Emollient Cream", brand: "Mustela", productType: "barrier repair", skinTypes: ["dry", "eczema-prone", "baby"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Mustela", "Stelatopia Emollient Cream")), ...e, imageUrl: "", tags: ["sunflower", "fragrance-free"] },
  { id: "bioderma-atoderm-intensive-balm", name: "Atoderm Intensive Balm", brand: "Bioderma", productType: "barrier repair", skinTypes: ["very-dry", "sensitive", "eczema-prone"], goals: ["barrier repair"], avoidFor: [], priceTier: "mid-range", productUrl: amazonProductSearch(productSearchQuery("Bioderma", "Atoderm Intensive Balm")), ...e, imageUrl: "", tags: ["lipid-complex", "fragrance-free"] },
  { id: "larocheposay-lipikar-balm-ap-plus", name: "Lipikar Balm AP+ Intense Repair Moisturizing Body & Face Cream", brand: "La Roche-Posay", productType: "barrier repair", skinTypes: ["dry", "sensitive", "eczema-prone"], goals: ["barrier repair", "hydration"], avoidFor: [], priceTier: "budget", productUrl: amazonProductSearch(productSearchQuery("La Roche-Posay", "Lipikar Balm AP+ Intense Repair Moisturizing Body & Face Cream")), ...e, imageUrl: "", tags: ["ceramide", "niacinamide"] },
];

export const skincareProductCount = skincareProducts.length;
